### ISSUE TITLE
A Writing errors

### ISSUE THREAD

**Issue by veraanddamao** [tensorlayer/tensorlayer#1002]
There may be a writing error in  https://github.com/tensorlayer/tensorlayer/blob/master/examples/text_generation/tutorial_generate_text.py
line 250 
: ‘train_weights = net.weights’ , I think this should be changed to ‘train_weights=net.trainable_weights’，Otherwise, the program will report errors on my computer.

**Comment by zsdonghao** [comment]
thanks I fixed it now

**Comment by veraanddamao** [comment]
Thanks for your tensorlayer.
