### ISSUE TITLE
Graphics/Geometry layers [NEED CONTRIBUTION]

### ISSUE THREAD

**Issue by zsdonghao** [tensorlayer/tensorlayer#1004]
We start to develop some new layers for Graphics, will need your help. Feel free to discuss in Slack [(invited link)](https://join.slack.com/t/tensorlayer/shared_invite/enQtMjUyMjczMzU2Njg4LWI0MWU0MDFkOWY2YjQ4YjVhMzI5M2VlZmE4YTNhNGY1NjZhMzUwMmQ2MTc0YWRjMjQzMjdjMTg2MWQ2ZWJhYzc).

# Normalisation
- [ ] AdaIN    Style-based GAN, HoloGAN
- [ ] SPatially-Adaptive (DE)normalization    SPADE 

# 3D
- [ ] RenderNet, see HoloGAN
- [ ] 3D Transformer, seeHoloGAN
- [ ] 3D to 2.5D Projector, see Visual Object Net

# Sampler /  Transformer
- [ ] Bilinear sampler: move pixels from the input image to the output image, and make it differentiable.
```
X = f(X, [[x,y], [x,y]...])
```
- [ ] `SpatialTransformerProjective2d`, we now only have `SpatialTransformerAffine2d`
 
# Examples
- [ ] HoloGAN
- [ ] Style-based GAN
- [ ] SPADE
- [ ] Visual Object Net

**Comment by joybhallaa** [comment]
@zsdonghao is this issue still up for grabs?

**Comment by zsdonghao** [comment]
@joybhallaa yes of course.

**Comment by joybhallaa** [comment]
@zsdonghao I'll like to take up this issue.

**Comment by zsdonghao** [comment]
oh, great! welcome to join us. let us know if you need any discussions.


@luomai @lgarithm @warshallrho @Laicheng0830

**Comment by joybhallaa** [comment]
@zsdonghao can you point me to some resources for HoloGAN and AdaIN? 
Also, can I message you guys on slack?

**Comment by zsdonghao** [comment]
@joybhallaa hi, sure, see you on slack.
