### ISSUE TITLE
The "quan_conv_bn.py" didn't update.

### ISSUE THREAD

**Issue by edwardzcl** [tensorlayer/tensorlayer#1005]
The class "QuanConv2dWithBN" didn't update, it still use TL1.x defination.

Following the Path:
https://github.com/tensorlayer/tensorlayer/blob/master/tensorlayer/layers/convolution/quan_conv_bn.py

You can compare "quan_conv.py" and "quan_conv_bn.py" to find the difference.

**Comment by zsdonghao** [comment]
it is in the todo list here https://github.com/tensorlayer/tensorlayer/issues/956
