### ISSUE TITLE
The comment in "simplified_conv.py"  may have a error.

### ISSUE THREAD

**Issue by edwardzcl** [tensorlayer/tensorlayer#1006]
In "simplified_conv.py", the parameter in class "Conv1d", "Conv2d" and  "Conv3d" may have a error, ie. stride should be strides.

Following the path:
https://github.com/tensorlayer/tensorlayer/blob/master/tensorlayer/layers/convolution/simplified_conv.py

The comment code is like:

    With TensorLayer
    >>> net = tl.layers.Input([8, 100, 1], name='input')
    >>> conv1d = tl.layers.Conv1d(n_filter=32, filter_size=5, stride=2, b_init=None, in_channels=1, name='conv1d_1')
    >>> print(conv1d)
    >>> tensor = tl.layers.Conv1d(n_filter=32, filter_size=5, stride=2, act=tf.nn.relu, name='conv1d_2')(net)
    >>> print(tensor)

refer to code line 51 or 53 in "simplified_conv.py" for location.

**Comment by JingqingZ** [comment]
Thanks for reporting this! The bugs have been fixed in PR#1007.
