### ISSUE TITLE
How to migrate tf.contrib.layers.layer_norm

### ISSUE THREAD

**Issue by pusabre** [tensorlayer/tensorlayer#1020]
Hi everyone, 

I am trying to migrate some TF 1.13 code to TF 2.0 I am working on Mac OSX. 

I am stuck how to convert following function:
```python
tf.contrib.layers.layer_norm(inputs=input_tensor, begin_norm_axis=-1, begin_params_axis=-1, scope=name)
```
Here should be used `LayerNorm` class from here https://tensorlayer.readthedocs.io/en/latest/_modules/tensorlayer/layers/normalization.html
I have tried the following:
```python
LayerNorm(begin_norm_axis=-1).build(input_tensor.shape).forward(inputs=input_tensor)
```
but it throws some errors:
```
AttributeError: 'NoneType' object has no attribute 'forward'
```
For some reason, this API was skipped when I ran the `tf_upgrade_v2` tool for migration together with dozens of other classes. Not clear why. 

I can not figure out where the error is. The error message is clear, but I can not figure out why it happens. The stacktrace does not show any TF related code, so api call tree only shows code in my project back to `tf.contrib.layers.layer_norm` function when it breaks.
So, could someone please give some hints about how to correct it?

PS: This is not an issue, but I can not label this ticket with `help_wanted` label.

**Comment by ChrisWu1997** [comment]
The reason behind this error is clear: the `build` function of `Layer` has no return value but you call `forward` upon that, which results in accessing an attribute of `None` object.  

The `build` / `forward` function is not supposed to be called explicitly by user. If you just want to use `LayerNorm` as one intermediate layer of your model, use it in a normal way as in the doc  [here](https://tensorlayer.readthedocs.io/en/latest/user/get_start_model.html#define-a-model).

**Comment by pusabre** [comment]
Hi @ChrisWu1997 
Thank you for your answer. I was trying to migrate one application which uses Bert model and this is some internal logic in that code. As it seems, it might be faster to rewrite it from scratch with Bert implementation in TF 2.0 since there is a lot of code which can not be easily migrated without deep knowledge of internal logic.
Best,
Ljubisa.

**Comment by saipavanmeruga** [comment]
Hey  @pusabre 
Can you share the details on how you changed the code from tf.contrib.layers.layer_norm() to be compatible for TF2.0.0
