### ISSUE TITLE
请问能不能实现一机多GPU数据或者模型并行处理？

### ISSUE THREAD

**Issue by YonghuiXu** [tensorlayer/tensorlayer#1031]
### New Issue Checklist

- [ ] I have read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [ ] I searched for [existing GitHub issues](https://github.com/tensorlayer/tensorlayer/issues)

### Issue Description

[INSERT DESCRIPTION OF THE PROBLEM]

### Reproducible Code

- Which OS are you using ?
- Please provide a reproducible code of your issue. Without any reproducible code, you will probably not receive any help.

[INSERT CODE HERE]

```python
# ======================================================== #
###### THIS CODE IS AN EXAMPLE, REPLACE WITH YOUR OWN ######
# ======================================================== #

import tensorflow as tf
import tensorlayer as tl

x = tf.placeholder(tf.float32, [None, 64])
net_in = tl.layers.InputLayer(x)

net = tl.layers.DenseLayer(net_in, n_units=25, act=tf.nn.relu, name='relu1')

print("Output Shape:", net.outputs.get_shape().as_list()) ### Output Shape: [None, 25]

# ======================================================== #
###### THIS CODE IS AN EXAMPLE, REPLACE WITH YOUR OWN ######
# ======================================================== #
```

**Comment by zsdonghao** [comment]
Horvord supports tensorlayer

**Comment by YonghuiXu** [comment]
谢谢，我了解一下


 
---原始邮件---
发件人: "Hao"<notifications@github.com>
发送时间: 2019年7月26日(星期五) 晚上6:02
收件人: "tensorlayer/tensorlayer"<tensorlayer@noreply.github.com>;
抄送: "YonghuiXu"<2259949930@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [tensorlayer/tensorlayer] 请问能不能实现一机多GPU数据或者模型并行处理？ (#1031)



Horvord supports tensorlayer
