### ISSUE TITLE
Seq2seq : the problem of generality

### ISSUE THREAD

**Issue by zsdonghao** [tensorlayer/tensorlayer#1047]
Hi, I found some feedbacks regarding the updated Seq2seq from the users.

The updated code as the following (from [seq2seq-chatbot](https://github.com/tensorlayer/seq2seq-chatbot/blob/dynamic/main.py))does not allow users to define their embedding/encoding processes. It will have a problem in the applications like language translation in which two different embeddings should be applied for different languages or the video application in which the input of RNN for encoding the decoding can be different types of data. 

```python
model_ = Seq2seq(
        decoder_seq_length = decoder_seq_length,
        cell_enc=tf.keras.layers.GRUCell,
        cell_dec=tf.keras.layers.GRUCell,
        n_layer=3,
        n_units=256,
        embedding_layer=tl.layers.Embedding(vocabulary_size=vocabulary_size, embedding_size=emb_dim),
        )

output = model_(inputs = [X, _decode_seqs], dec_len = dec_len, enc_len = enc_len)
```

Here is the old code for reference, it allows users to input their encoders, such as one or two embeddings or CNN models.

```python
def create_model(encode_seqs, decode_seqs, src_vocab_size, emb_dim, is_train=True, reuse=False):
    with tf.variable_scope("model", reuse=reuse):
        # for chatbot, you can use the same embedding layer,
        # for translation, you may want to use 2 seperated embedding layers
        with tf.variable_scope("embedding") as vs:
            net_encode = EmbeddingInputlayer(
                inputs = encode_seqs,
                vocabulary_size = src_vocab_size,
                embedding_size = emb_dim,
                name = 'seq_embedding')
            vs.reuse_variables()
            net_decode = EmbeddingInputlayer(
                inputs = decode_seqs,
                vocabulary_size = src_vocab_size,
                embedding_size = emb_dim,
                name = 'seq_embedding')
            
        net_rnn = Seq2Seq(net_encode, net_decode,
                cell_fn = tf.nn.rnn_cell.LSTMCell,
                n_hidden = emb_dim,
                initializer = tf.random_uniform_initializer(-0.1, 0.1),
                encode_sequence_length = retrieve_seq_length_op2(encode_seqs),
                decode_sequence_length = retrieve_seq_length_op2(decode_seqs),
                initial_state_encode = None,
                dropout = (0.5 if is_train else None),
                n_layer = 3,
                return_seq_2d = True,
                name = 'seq2seq')

        net_out = DenseLayer(net_rnn, n_units=src_vocab_size, act=tf.identity, name='output')
    return net_out, net_rnn
```

My suggestion is either change the name `Seq2seq` to `VanillaSeq2seq` or let it supports customised inputs as in the pass.

**Comment by JingqingZ** [comment]
I would suggesting writing a new `Seq2Seq` model which supports customised encoding/embedding of data for the Encoder and Decoder in `Seq2Seq`.

**Comment by ChrisWu1997** [comment]
I agree with @zsdonghao about the customized embedding things. Pytorch's newly updated [Transformer](https://pytorch.org/docs/stable/nn.html#transformer) does not include the embedding step and this feature really helps me a lot in my recent work. I believe there are many scenarios where people use `Seq2seq`/`Transformer` for customized tasks other than language modeling.

**Comment by luomai** [comment]
@ChrisWu1997 @zsdonghao after we release the API, we need to keep it stable unless there is a bug. This is typical in maintaining a project used by many people.

For supporting new features, the best way is to add a new layer. This is a win-win solution as it satisfy you and does not affect existing users. I remember that we have a feed forward layer for transformers. We can follow the same way. 

If you really, really feel the current seq2seq API has flaws, we can consider to mark it deprecated snd encourage users to use the new customisable seq2seq.

**Comment by zsdonghao** [comment]
@luomai If we have to keep everything stable .. why should we release TensorLayer 2.0 .. we should open a new repo to create a new library then. 

We can modify Seq2seq, so that if someone use it in old way, we raise an error.

**Comment by luomai** [comment]
That is why we release TL 2 (1->2) because of the braking changes of APIs.

**Comment by JingqingZ** [comment]
Changing APIs of a large repo like TL which has lots of users should always have  your greatest discreetness. We should be considerable as this change will potentially affect lots of other users once they upgrade.
