### ISSUE TITLE
Discrete SAC

### ISSUE THREAD

**Issue by junhuang-ifast** [tensorlayer/tensorlayer#1048]
Hi, I saw that u written [https://github.com/tensorlayer/tensorlayer/tree/reinforcement-learning/examples/reinforcement_learning](here) here that this tensorflow version of SAC supports discrete action spaces as well? Could u point me to where its implemented, as im having trouble locating it. Thanks !

![image](https://user-images.githubusercontent.com/47650501/66885542-30763000-f007-11e9-9ac4-35aec1608535.png)

**Comment by zsdonghao** [comment]
we don't have the example for SAC with discrete space, but you can just simply modify it from the continuous space 

https://github.com/tensorlayer/tensorlayer/blob/master/examples/reinforcement_learning/tutorial_SAC.py

check this may help:https://github.com/tensorlayer/tensorlayer/blob/master/examples/reinforcement_learning/tutorial_PG.py

**Comment by junhuang-ifast** [comment]
@zsdonghao is there any plans to incorporate support for multiple discrete action in SAC ?

**Comment by zsdonghao** [comment]
@JunbinWang  As I said, SAC supported multiple discrete already, you just need a small modification.

For users do not have any RL background, please refer to our ongoing project here: https://github.com/tensorlayer/RLzoo
