### ISSUE TITLE
Need new feature: model visualization

### ISSUE THREAD

**Issue by Akanesasu** [tensorlayer/tensorlayer#1051]
The function "plot_model" in keras.until which will plot a graph of the model and save it to a file is really useful, especially when you want to look at the model you just built or when you are not sure about the i/o shape of a layer. 
The graph of the model is also very nice(maybe?) and it can make the beginners of DL satisfied looking at the model they built. 
So I think maybe tensorlayer can also have similar functions, why not? please!

**Comment by Akanesasu** [comment]
Sorry for my crappy English writing :(

**Comment by zsdonghao** [comment]
@Laicheng0830 fyi

**Comment by Laicheng0830** [comment]
Thanks for your suggestion, I will try to add this feature in the new version.

**Comment by zkx741481546** [comment]
> 感谢您的建议，我将尝试在新版本中添加此功能。

the function like Keras summary() is good enough, I hope the visualization can show each layer's input and output tensor's shape

**Comment by zsdonghao** [comment]
you can also print the configuration via:

```
print(model)
```

**Comment by zkx741481546** [comment]
> you can also print the configuration via:
> 
> ```
> print(model)
> ```

But it can not show the feature map's width and hight, the visualization like keras summary is really convenient.
