### ISSUE TITLE
Do we have a slack channel?

### ISSUE THREAD

**Issue by bokutotu** [tensorlayer/tensorlayer#1059]

**Comment by zsdonghao** [comment]
check readme

**Comment by Hika-Kondo** [comment]
Link in README may not be active

**Comment by zsdonghao** [comment]
https://join.slack.com/t/tensorlayer/shared_invite/enQtODk1NTQ5NTY1OTM5LTQyMGZhN2UzZDBhM2I3YjYzZDBkNGExYzcyZDNmOGQzNmYzNjc3ZjE3MzhiMjlkMmNiMmM3Nzc4ZDY2YmNkMTY

i will update the readme as well
