### ISSUE TITLE
Is PPO still applicable if the length of each trajectory is different?

### ISSUE THREAD

**Issue by YingxiaoKong** [tensorlayer/tensorlayer#1074]
### New Issue Checklist

- [ ] I have read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [ ] I searched for [existing GitHub issues](https://github.com/tensorlayer/tensorlayer/issues)

### Issue Description

[INSERT DESCRIPTION OF THE PROBLEM]

### Reproducible Code

- Which OS are you using ?
- Please provide a reproducible code of your issue. Without any reproducible code, you will probably not receive any help.

[INSERT CODE HERE]

```python
# ======================================================== #
###### THIS CODE IS AN EXAMPLE, REPLACE WITH YOUR OWN ######
# ======================================================== #

import tensorflow as tf
import tensorlayer as tl

x = tf.placeholder(tf.float32, [None, 64])
net_in = tl.layers.InputLayer(x)

net = tl.layers.DenseLayer(net_in, n_units=25, act=tf.nn.relu, name='relu1')

print("Output Shape:", net.outputs.get_shape().as_list()) ### Output Shape: [None, 25]

# ======================================================== #
###### THIS CODE IS AN EXAMPLE, REPLACE WITH YOUR OWN ######
# ======================================================== #
```

Hi in the paper I have read, they all said the trajectories should have the same length, or a 'fixed length'. I may misunderstand this meaning. But in all the codes I saw, they all make a fixed length for each episode. Can PPO still work if the length is different?

**Comment by zsdonghao** [comment]
Hi, I highly recommend TL2.0, so you can use the new RL code

**Comment by YingxiaoKong** [comment]
Thanks! I will have a look at it now!
________________________________

**Comment by quantumiracle** [comment]
Hi,
PPO generally does not require the length of trajectory to be fixed/same, for update in either a batch manner or based on samples a single episode/trajectory. As PPO has on-policy update process, the update may not take a batch (usually applied in off-policy algorithms like DDPG, SAC) but a single episodic trajectory, as shown in our [tutorial](https://github.com/tensorlayer/tensorlayer/blob/93905f057e74d87be7c7d29de40ef917b758db8e/examples/reinforcement_learning/tutorial_PPO.py#L155). So the length of  trajectory is never required to be fixed, the trajectory will finish once it's *done*. Note that for other implementations in which PPO is updated in a batch manner, a fixed length is also not required, a batch filled with samples from different trajectories can be created.
