### ISSUE TITLE
a bug in tutorial_prioritized_replay.py?

### ISSUE THREAD

**Issue by hanbaoan123** [tensorlayer/tensorlayer#1084]
![image](https://user-images.githubusercontent.com/32160782/82730287-1769f600-9d31-11ea-9100-a600306f390f.png)

Another parameter (weight w) should be input into the train funtion when using dqn with prioritized_replay.

**Comment by Officium** [comment]
The implementation of `PrioritizedReplayBuffer` stores prioritized weights in variable `transitions`. See a comparison between [PrioritizedReplayBuffer.sample](https://github.com/tensorlayer/tensorlayer/blob/93905f057e74d87be7c7d29de40ef917b758db8e/examples/reinforcement_learning/tutorial_prioritized_replay.py#L357) and  [ReplayBuffer.sample](https://github.com/tensorlayer/tensorlayer/blob/93905f057e74d87be7c7d29de40ef917b758db8e/examples/reinforcement_learning/tutorial_prioritized_replay.py#L297).
