### ISSUE TITLE
remove prioritized replay from tutorial_DQN_variants.py?

### ISSUE THREAD

**Issue by hanbaoan123** [tensorlayer/tensorlayer#1095]
### New Issue Checklist

- [√ ] I have read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [√ ] I searched for [existing GitHub issues](https://github.com/tensorlayer/tensorlayer/issues)

### Issue Description

Hava removed the prioritized replay from tutorial_DQN_variants.py？I wonder why do this modification.

**Comment by quantumiracle** [comment]
Hi, 
Please check [here](https://github.com/tensorlayer/tensorlayer/blob/master/examples/reinforcement_learning/tutorial_prioritized_replay.py). The prioritized experience replay is demonstrated in an individual script.
