### ISSUE TITLE
Performance issue in the definition of read_and_decode, examples/data_process/tutorial_tfrecord.py(P1)

### ISSUE THREAD

**Issue by DLPerf** [tensorlayer/tensorlayer#1140]
Hello, I found a performance issue in the difinition of `read_and_decode`, examples/data_process/tutorial_tfrecord.py, [tf.io.FixedLenFeature](https://github.com/tensorlayer/tensorlayer/blob/73a42a3c4da03715673adb55523c66a7ad826067/examples/data_process/tutorial_tfrecord.py#L83) will be called repeately during the program execution, resulting in reduced efficiency. So I think the dictionary should be created before the loop.

The same issues exist [line 69 &70](https://github.com/tensorlayer/tensorlayer/blob/73a42a3c4da03715673adb55523c66a7ad826067/examples/data_process/tutorial_tfrecord2.py#L69), and [line 258 & 259 ](https://github.com/tensorlayer/tensorlayer/blob/73a42a3c4da03715673adb55523c66a7ad826067/examples/text_word_embedding/tutorial_word2vec_basic.py#L258).

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by DLPerf** [comment]
@hanjr92 Hi, bro, could you consider the issue?

**Comment by hanjr92** [comment]
Thanks! like this ?:
`def read_and_decode(filename):
    # generate a queue with a given file name
    raw_dataset = tf.data.TFRecordDataset([filename]).shuffle(1000).batch(4)
    features = {}
    for serialized_example in raw_dataset:
        features['label'] = tf.io.FixedLenFeature([], tf.int64)
        features['img_raw'] = tf.io.FixedLenFeature([], tf.string)
        features = tf.io.parse_example(serialized_example, features)
        # You can do more image distortion here for training data
        img_batch = tf.io.decode_raw(features['img_raw'], tf.uint8)
        img_batch = tf.reshape(img_batch, [4, 224, 224, 3])
        # img = tf.cast(img, tf.float32) * (1. / 255) - 0.5
        label_batch = tf.cast(features['label'], tf.int32)
        yield img_batch, label_batch
`

> @hanjr92 Hi, bro, could you consider the issue?

**Comment by hanjr92** [comment]
Thanks！I will modify them.
```python
def read_and_decode(filename):
    # generate a queue with a given file name
    raw_dataset = tf.data.TFRecordDataset([filename]).shuffle(1000).batch(4)
    features = {}
    for serialized_example in raw_dataset:
        features['label'] = tf.io.FixedLenFeature([], tf.int64)
        features['img_raw'] = tf.io.FixedLenFeature([], tf.string)
        features = tf.io.parse_example(serialized_example, features)
        # You can do more image distortion here for training data
        img_batch = tf.io.decode_raw(features['img_raw'], tf.uint8)
        img_batch = tf.reshape(img_batch, [4, 224, 224, 3])
        # img = tf.cast(img, tf.float32) * (1. / 255) - 0.5
        label_batch = tf.cast(features['label'], tf.int32)
        yield img_batch, label_batch
```

**Comment by hanjr92** [comment]
@DLPerf
