### ISSUE TITLE
module 'tensorflow.python.framework.ops' has no attribute '_TensorLike' , This error is reported after the program runs

### ISSUE THREAD

**Issue by imitatorgkw** [tensorlayer/tensorlayer#1149]
i run tutorial_A3C.py
An error occurred
module 'tensorflow.python.framework.ops' has no attribute '_TensorLike' 
What should I do
tensorflow=2.3
tensorlayer=0.11.1

**Comment by Laicheng0830** [comment]
Install the latest version of tensorlayer from the source and this problem will be solved.

**Comment by imitatorgkw** [comment]
![image](https://user-images.githubusercontent.com/46749593/139529764-01d52cd8-c651-47e9-ab67-d840fca3d774.png)
I've updated it, but the problem hasn't been solved

**Comment by Laicheng0830** [comment]
tensorlayer2.2.3 is no longer the latest version, please install it from the source code.
pip3 install git+https://github.com/tensorlayer/tensorlayer.git

**Comment by Laicheng0830** [comment]
FYI

https://github.com/tensorlayer/srgan/issues/214#issuecomment-684766733

**Comment by imitatorgkw** [comment]
it can run, thank you
