### ISSUE TITLE
how to get current layer parameters

### ISSUE THREAD

**Issue by arisliang** [tensorlayer/tensorlayer#115]
It would be easier to get current layer's parameters, rather than picking it from all layer's parameters. Something like layer.outputs that contains current layer's outputs.

**Comment by wagamamaz** [comment]
for denselayer, please use `network.all_params[-2:]`

**Comment by Xls1994** [comment]
Maybe you can use layers.all_params() to get a list of Tensor, which all network variables in order.

**Comment by arisliang** [comment]
It can be retrieved via layers.all_params, but it's inconvenient, as we have to keep track of which layer does the current layer points to. It'd be better if it just returns current layer, like the outputs does.
Perhaps something called layers.params that returns [W,b]?

**Comment by zsdonghao** [comment]
Three ways can do this.

1. get current output `network.outputs`
2. get all outputs `network.all_params`
3. get all outputs by a given layer name `tl.layers.get_layers_with_name(network, "dense")`
