### ISSUE TITLE
AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'

### ISSUE THREAD

**Issue by jaried** [tensorlayer/TensorLayer#1153]
### New Issue Checklist

- I have read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- I searched for [existing GitHub issues](https://github.com/tensorlayer/tensorlayer/issues)

### Issue Description

AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'

### Reproducible Code

- OS: windows 10 professional
- Please provide a reproducible code of your issue. Without any reproducible code, you will probably not receive any help.

[tutorial_PG.py](https://github.com/tensorlayer/tensorlayer/blob/master/examples/reinforcement_learning/tutorial_PG.py)

line 213, in __init__
    if isinstance(check_argu, tf_ops._TensorLike) or tf_ops.is_dense_tensor_like(check_argu):
AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'

**Comment by Laicheng0830** [comment]
This problem has been solved in version 2.2.5, please update to version 2.2.5

**Comment by Laicheng0830** [comment]
@jaried This problem has been solved in version 2.2.5, please update to version 2.2.5

**Comment by jaried** [comment]
Thanks, it works.
