### ISSUE TITLE
ConvLayer cannot specify the data_format 

### ISSUE THREAD

**Issue by boscotsang** [tensorlayer/tensorlayer#124]
https://www.tensorflow.org/versions/master/api_docs/python/tf/nn/conv2d

tf.nn.conv2d can receive the `data_format` argument to specify the data format. However, tl.layers.Conv2dLayer doesn't receive such an argument.

**Comment by zsdonghao** [comment]
@boscotsang hi , thank you for your suggestion, please check my new commit ~

**Comment by boscotsang** [comment]
@zsdonghao Thank you. Besides conv2d, PoolLayer has the similar problem. I also found that the function MeanPoolxx/MaxPoolxx is a wrapper of tf.contrib.layers and the default argument `data_format` of MeanPoolxx/MaxPoolxx is "channels_last". However, according https://www.tensorflow.org/versions/r1.1/api_docs/python/tf/contrib/layers/avg_pool2d the argument `data_format` is either `NCHW` nor `NHWC`.
