### ISSUE TITLE
Issues about get_layers_with_name

### ISSUE THREAD

**Issue by zhimingluo** [tensorlayer/tensorlayer#134]
The method tl.layers.get_layers_with_name which is not return the layer object, only return the output Tensor `layer.outputs`, which is not convenient to when you want to add some new layers on the top of  an arbitrary layer, such as the code below.

x = tf.placeholder(tf.float32, [None, 224, 224, 3])
network = tl.layers.InputLayer(inputs=x,name='input_layer')
network = tl.layers.Conv2d(network, n_filter=32, filter_size=[3, 3], name='conv1')
conv1 = tl.layers.get_layers_with_name(network, 'conv1')[0]
conv2 = tl.layers.Conv2d(conv1, n_filter=64, filter_size=[3, 3], name='conv2')

**Comment by zsdonghao** [comment]
yes, it only return the corresponding `layer.outputs`, if you want it to be a `Layer` class, you can put it into `InputLayer`.
