### ISSUE TITLE
RNN layers don't work when output units != hidden state units

### ISSUE THREAD

**Issue by cai-lw** [tensorlayer/tensorlayer#145]
According to [the documentation of tf.contrib.rnn.RNNCell](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/RNNCell), there is no guarantee that an RNN cell has the same number of output units as hidden state units.

I know that in common use cases they are almost always equal, but when I write a custom RNN cell which outputs its internal state alongside the ordinary output (and thus has more output units than hidden state units), all RNN layer APIs fail to work because they do many incorrect reshaping.

For example (part of [DynamicRNNLayer](https://github.com/zsdonghao/tensorlayer/blob/master/tensorlayer/layers.py#L4003)):
```python
          with tf.variable_scope(name, initializer=initializer) as vs:
            outputs, last_states = tf.nn.dynamic_rnn(
                cell=self.cell,
                # inputs=X
                inputs = self.inputs,
                # dtype=tf.float64,
                sequence_length=sequence_length,
                initial_state = self.initial_state,
                **dynamic_rnn_init_args
                )
            rnn_variables = tf.get_collection(TF_GRAPHKEYS_VARIABLES, scope=vs.name)

            # print("     n_params : %d" % (len(rnn_variables)))
            # Manage the outputs
            if return_last:
                # [batch_size, n_hidden]
                # outputs = tf.transpose(tf.pack(outputs), [1, 0, 2]) # TF1.0 tf.pack --> tf.stack
                self.outputs = advanced_indexing_op(outputs, sequence_length)
            else:
                # [batch_size, n_step(max), n_hidden]
                # self.outputs = result[0]["outputs"]
                # self.outputs = outputs    # it is 3d, but it is a list
                if return_seq_2d:
                    # PTB tutorial:
                    # 2D Tensor [n_example, n_hidden]
                    try: # TF1.0
                        self.outputs = tf.reshape(tf.concat(outputs, 1), [-1, n_hidden])
                    except: # TF0.12
                        self.outputs = tf.reshape(tf.concat(1, outputs), [-1, n_hidden])
                else:
                    # <akara>:
                    # 3D Tensor [batch_size, n_steps(max), n_hidden]
                    max_length = tf.shape(outputs)[1]
                    batch_size = tf.shape(outputs)[0]


                    try: # TF1.0
                        self.outputs = tf.reshape(tf.concat(outputs, 1), [batch_size, max_length, n_hidden])
                    except: # TF0.12
                        self.outputs = tf.reshape(tf.concat(1, outputs), [batch_size, max_length, n_hidden])
```
The Tensorflow API `tf.nn.dynamic_rnn` actually handles dimensions correctly, but these `n_hidden`s in reshaping messed it up. They should be replaced by something like `tf.shape(outputs)[-1]`.

This seems to be a low priority bug, but I feel like that I am urged to fix it. Do you think it is necessary? @zsdonghao

**Comment by zsdonghao** [comment]
@cai-lw thank you for your report, do you mean you would like to change 
`self.outputs = tf.reshape(tf.concat(outputs, 1), [-1, n_hidden])` to `self.outputs = tf.reshape(tf.concat(outputs, 1), [-1, tf.shape(outputs)[-1]])` ?

**Comment by cai-lw** [comment]
@zsdonghao Yes, this should work.
