### ISSUE TITLE
attention seq2seq need

### ISSUE THREAD

**Issue by superhy** [tensorlayer/tensorlayer#164]

**Comment by zsdonghao** [comment]
i mark this issue as `help wanted`, if any one used TF's dynamic RNN encoder and attention seq2seq, feel free to contribute ~

**Comment by superhy** [comment]
if I want to input the embedding matrix which trained by myself with the other API(like Gensim), I don't want use embedding layer in TL even TF, I want call the clear attention seq2seq or Peekly seq2seq directly.

**Comment by superhy** [comment]
In the other words, EmbeddingAttentionSeq2seqWrapper function which like the project "easy_seq2seq" is too low in TF-version
