### ISSUE TITLE
Explicit interface of getting vocabulary size?

### ISSUE THREAD

**Issue by joemzhao** [tensorlayer/tensorlayer#183]
Hi zsdonghao, first of all thanks for the great work!

I am wondering if you though it is better to return the vocabulary size explicitly? https://github.com/zsdonghao/tensorlayer/blob/master/tensorlayer/nlp.py#L397

It could be useful when the preprocessing is done together with main training trunk instead of finished separately at the beginning.

Thanks!

**Comment by zsdonghao** [comment]
If we return the vocabulary size, i think the back compability may have problem.
