### ISSUE TITLE
Improvement TensorDB : remove hard dependency on mongoDB  and make it loose.

### ISSUE THREAD

**Issue by arita37** [tensorlayer/tensorlayer#198]
Given the general philosophy of TensorDB to connect DB based on query,
to remove strong dependency on DB framework.
TensorDB : Astract layer which encapsulates DB connection :  (Stream data, large Blob data, ...).

Having dependency on MongoDB is a pain, 
because we may use other DB framework: Big Query, Postgres, MySQL, Aurora, ....

It would be better to have general abstract layer and add specification for the DB platform
through engine definition (like in SQL Alchemy):
http://docs.sqlalchemy.org/en/latest/core/engines.html

engine= create_engine(type="MongoDB", connection_string="   ")
engine= create_engine(type="filesystem", connection_string="   ")
engine= create_engine(type="AWSAurora", connection_string="   ")

db= TensorDB(engine=engine, .... )
...

It allows to add new connector without the need of changing the abstraction layer,
like in SQL Alchemy.

So, you can mix NO SQL DB with SQL DB as well as filesystem

**Comment by fangde** [comment]
Dear arita:
thank you for the comment,
that is exactly I'm doing now.
we have not merge the db code to the Tensorlayer
https://github.com/fangde/TensorLab

**Comment by arita37** [comment]
Difficulty would be to define correctly the abstract layer for differene end DB:
   SQLDB  vs NoSQL DB vs filestorage,    Streaming data vs No Streaming.

Also differenciate:
    model storage (issue with TF dependency ... loading model with TF 2.0 when saved with TF 1.2 )
    Input data  image/video/text/numerical.

Is there a doc/a way to see the abstract interface methods ?

**Comment by fangde** [comment]
there is a code in the upstream. 
I am thinking using GraphQL

**Comment by arita37** [comment]
GraphQL looks interesting, maybe it has to compare with  ProtocolBuffer : 
   TF is using ProtocolBuffer and it looks better for large data serialization: 
   https://developers.google.com/protocol-buffers/

Additionnally, there is already blaze/odo who supports a certain number of backend including mongo and SQLDB :  https://goo.gl/Vy2859

Few other questions to consider:
   Interface API TensorLayer with TensorDB.
   Interface API TensorDB with Backend (abstraction of backend).
   Scope in term of data pre-processing :  how much in TL side, TensorDB side and Backend side ?
   Data fetching :  Sync / async
                             Local storage of data  : format(s) ?

Maybe, it might easier to discuss in gitter for the details, 
https://gitter.im/

Thanks for starting the contribution, it would help from reinventing the "wheel" every time 
we do a new training....
