### ISSUE TITLE
How to use data with dtype=tf.float16?

### ISSUE THREAD

**Issue by ExonRen** [tensorlayer/tensorlayer#206]
Due to the large amount and big size of data, I'm considering using `tf.float16` for a higher speed. But all the variables used in all the layers are generated by `tf.get_variable()` with `dtype=None` as default. And simply modifying the input placeholder to `tf.float16` will lead to `tf.cast()` error:
> ValueError: Tensor conversion requested dtype float32 for Tensor with dtype float16

Then I modified all of the `tf.get_variable()` in the layers I use to add the option `dtype=tf.float16`, **including the weight and bias in Conv/DeConv, as well as the `beta`, `gamma`, `moving_mean` and `moving_variance` in BatchNorm**. Any of these above, if left unchanged, will still cause the `tf.cast()` error. I also use Pool, Elementwise and Dropout but they seem to do nothing with `tf.get_variable()`. **However now the training loss become `nan` right after the first batch, though it can run without error at least.**

So what else should I do to run with `tf.float16`? Or is there any other easier approach instead of modifying the TensorLayer code?

Thank you.

**Comment by zsdonghao** [comment]
Hi, i believe changing the weight/bias in Conv/DeConv to float16 would not lead to this error, could you use float32 in BatchNormLayer to see whether it raise this error?

What is your placeholder dtype?

**Comment by ExonRen** [comment]
Hi,

If I only change the dtype of weight/bias in Conv/DeConv to float16 and left BatchNorm float32, it will throw the `tf.cast()` error. I even tried leave any of the four variables (beta, gamma, moving_mean and moving_variance) unchanged but find all of them have to be changed or there will come `tf.cast()` error.

And the placeholder dtype is always set to float16 in all occasions I mentioned above.

**Comment by zsdonghao** [comment]
em... I think a better way is to try without BatchNorm, that should be some small issue here.

**Comment by ExonRen** [comment]
Alright... In fact BatchNorm plays an important role in my network, so maybe I'll just keep using float32 currently.

Thank you anyway and expecting any fix.

**Comment by zsdonghao** [comment]
You are welcome, feel free to let me know if you want discussion, I also want to know how to make it work~.

**Comment by zsdonghao** [comment]
@ExonRen Hi, I just release an example for float16 model using Conv2d, BatchNorm and Dense

https://github.com/zsdonghao/tensorlayer/blob/master/example/tutorial_mnist_float16.py

Hope it can solve your problem~

**Comment by korigod** [comment]
@zsdonghao's tutorial was moved to https://github.com/tensorlayer/tensorlayer/blob/master/examples/basic_tutorials/tutorial_mnist_float16.py.

**Comment by korigod** [comment]
@zsdonghao's example was moved to https://github.com/tensorlayer/tensorlayer/blob/master/examples/basic_tutorials/tutorial_mnist_float16.py.
