### ISSUE TITLE
Can't load weights by load_and_assign_npz_dict in GAN

### ISSUE THREAD

**Issue by ShieLian** [tensorlayer/tensorlayer#213]
There're some methods need to pretrain G net and D net separately, then combine them to train together.  However, when I pretrain my net, I didn't notice that the api of tl.files have changed, so I use save_npz_dict to store my weights. But it seems that load_and_assign_npz_dict can't load&assign weights of G&D net separately. Is there any way to use those pretrained weights without retrain?

**Comment by zsdonghao** [comment]
Hi, yes.
This is a example to restore and save G and D via `tl.files.load_and_assign_npz` and `tl.files.save_npz`.

https://github.com/zsdonghao/SRGAN/blob/master/main.py

**Comment by ShieLian** [comment]
Thanks a lot, but could you please add some kind of util function to convert npz_dict in old version(which are 0,1,2,3..... named) to new format(named by param names)? This may be done by 1) use the network model, load the weights of old format  2) save those weights in new format
