### ISSUE TITLE
Cannot use Dropout Layer when I use tf.contrib.data.TFRecordDataset API

### ISSUE THREAD

**Issue by VisanXJ** [tensorlayer/tensorlayer#222]
HI~
I coded as [tensorflow offical guide ](https://www.tensorflow.org/programmers_guide/datasets); At begging, I hadn't add dropout layer but DenseLayer, everything OK. But next time I added DropoutLayer  in my Model Funtion, program said that "InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'tower_0/model/Placeholder' with dtype float";
I guess because of dataset API I used  caused that situation. 
In your DropoutLayer API, you said must use placeholder but dataset API haven't it, dataset API use iterator to get element for training

code like below:
*********************************************************************************************************
net = tl.layers.InputLayer(image_batch, name='input')
......
......
......
net = tl.layers.FlattenLayer(net, name='flatten')    
net = tl.layers.DenseLayer(net, n_units=4096, act=tf.nn.relu, name='fc2_relu')
net = tl.layers.DropconnectDenseLayer(net, keep = 0.8,n_units=4096, act = tf.nn.relu, 
        name='dropconnect_relu1')
**********************************************************************************************************

 Is there appropriate way to work it out?

**Comment by zsdonghao** [comment]
hi, did you enable/disable the dropout layer in feed_dict? like [tutorial_mlp_dropout1.py](https://github.com/zsdonghao/tensorlayer/blob/master/example/tutorial_mlp_dropout1.py)

another way is to build 2 graphs for training and testing seperatly. like [tutorial_mlp_dropout2.py](https://github.com/zsdonghao/tensorlayer/blob/master/example/tutorial_mlp_dropout2.py)

**Comment by VisanXJ** [comment]
Got your point and I  added feed_dict in my code as attachment file shows; Program raised: TypeError('The value of a feed cannot be a tf.Tensor object. 'TypeError: The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, strings, lists, numpy ndarrays, or TensorHandles. )
So I check Tensorflow API, the return type of iterator.get_next() is Tensor as I though to be.   
So it must be wrong somewhere I don't know. Maybe caused by type of compatibility between Your API and TF1.3.   All that ,Thank you~
[TL_issue.zip](https://github.com/zsdonghao/tensorlayer/files/1403693/TL_issue.zip),
