### ISSUE TITLE
why the stacked timedistributed layer in tensorlayer doesn't work?

### ISSUE THREAD

**Issue by cbdbdd** [tensorlayer/tensorlayer#223]
`
import tensorlayer as tl
import tensorflow as tf
batch_size = 32
timestep = 20
input_dim = 100
x = tf.placeholder(dtype=tf.float32, shape=[batch_size, timestep,  input_dim], name="encode_seqs")
net = tl.layers.InputLayer(x, name='input')

net = tl.layers.TimeDistributedLayer(net, layer_class=DenseLayer, args={'n_units':50, 'name':'dense'}, name='time_dense')
net = tl.layers.TimeDistributedLayer(net, layer_class=DenseLayer, args={'n_units':50, 'name':'dense1'}, name='time_dense1')
`

**Comment by ZhuYunzong** [comment]
I got a similar problem.  However, I used the two TimedistributedLayer but they aren't  stacked. Do you get the  TraceBack "Variable timedense1/dense1/W" does not exit, or was not created with tf.get_variable(). Did you mean to set reuse=Node in varScope"? Have you coped with it ?
