### ISSUE TITLE
parameters of prepro.elastic_transform

### ISSUE THREAD

**Issue by scimg** [tensorlayer/tensorlayer#225]
The parameter mode is actually the one used by gaussian_filter. The one used by map_coordinates is better to be added for data extraplanation.

**Comment by zsdonghao** [comment]
sorry, i didn't get your point.

**Comment by scimg** [comment]
The elastric_tranform function uses map_coordinates to do pixel mapping, the function "map_coordinates" has a parameter "mode" which determines what value will be used to fill the missing pixels. By default, constant mode and 0 filling will be used.

**Comment by geometrikal** [comment]
@scimg Do you want to have "mode" in the parameters for elastic_transform, then pass it on?

**Comment by scimg** [comment]
@geometrikal Yes, 0 filling looks not so good.
