### ISSUE TITLE
provide an official docker image for tensorlayer

### ISSUE THREAD

**Issue by lgarithm** [tensorlayer/tensorlayer#250]
Proposal:
provide an official docker image for tensorlayer and publish it on docker hub, so tensorlayer will be more universally accessible by cloud users.

This issue will discuss the detailed plan, including instructions on how to release the docker image.

**Comment by lgarithm** [comment]
https://github.com/zsdonghao/tensorlayer/pull/249 added the Dockerfile, so a docker image can be built with:

`docker build -t tensorlayer/tensorlayer .`

or 

`docker build -t tensorlayer/tensorlayer:1.7.2 .`

for specific tag.

**Comment by lgarithm** [comment]
for gnu image, use the following commands to build:

```
docker build -t tensorlayer/tensorlayer:latest-gpu  -f Dockerfile.gpu .
docker build -t tensorlayer/tensorlayer:1.7.2-gpu  -f Dockerfile.gpu .
```

**Comment by lgarithm** [comment]
We still need to setup auto build for docker image.

**Comment by lgarithm** [comment]
Action items: 

* [ ] convert the dockerhub account of tensorlayer to an org
* [ ] setup auto build

**Comment by luomai** [comment]
According to @zsdonghao we also need to provide a small article to show how to run a simple mnist example in a docker.

**Comment by DEKHTIARJonathan** [comment]
@lgarithm @luomai I will close this issue because Docker is implemented.
I will shortly update my blog with an article on this topic. It just need minor adaptation: https://www.born2data.com
