### ISSUE TITLE
Use Python linters to check syntax

### ISSUE THREAD

**Issue by luomai** [tensorlayer/tensorlayer#261]
An option is to use: https://github.com/DonJayamanne/pythonVSCode

**Comment by lgarithm** [comment]
actions items:
* fix import orders
* fix spacing, line break, etc.
* fix other warnings produced by a linter (e.g. pep8, pylint) as much as we can
* enforce style check on code review

**Comment by lgarithm** [comment]
[yapf](https://pypi.python.org/pypi/yapf) looks promising

**Comment by lgarithm** [comment]
[isort](https://pypi.python.org/pypi/isort) can be used for sorting imports

**Comment by luomai** [comment]
start with formatting the utils.py.

@zsdonghao @lgarithm

**Comment by luomai** [comment]
done with core lib files.

tutorial files remained untouched.
