### ISSUE TITLE
Transfer Learning

### ISSUE THREAD

**Issue by nickbent** [tensorlayer/tensorlayer#263]
I am trying to do transfer learning through the importing the TFslim libraries, I looked at the example code from the TFslim example but once it is imported into  tensorlayer I am not able to remove the final layers from the model. What I want to do is remove the last layers and replace them with a dense layer with 2 units (instead of 1001 for inception) is there anyway to do this? One way around this would be to freeze everything but the lasgt layers and retrain but just with the 2 examples and have all the other classes as empty but I'm hoping there must be a more elegant solution

**Comment by zsdonghao** [comment]
Hi, you may need to do something with `slim.arg_scope` 

Here is an example to remove some final layers from inception_v3, hope it solves your problem.

https://github.com/zsdonghao/Image-Captioning/blob/master/model.py

Happy new year!

**Comment by jorgemf** [comment]
Hi @nickbent, the process for transfer learning I do is as follow:

1. Create the model with the desired number of outputs (a number different from 1001 most probably)
2. Tell the optimizer to not train the variables that are not in the last layer, this is, train only the variables of the last layer (you might also want to retrain the whole graph with the initialization of an already trained model, it speeds up the training and give good results too)
3. Start the session and initilize the graph variables
4. Load from the checkpoint all the graph without the last layer (you can set the variables in the saver, even do a mapping between the names of the variables in the graph and in the file)
5. Do the normal training
