### ISSUE TITLE
'load_and_assign_npz' can't work in windows to load a npz file from linux

### ISSUE THREAD

**Issue by lsmale** [tensorlayer/tensorlayer#264]
I used the following command to save network parameters in the Ubuntu system:
tl.files.save_npz(net.all_params, name='name.npz', sess=sess)
Then, I use the following command to load network parameters in the Windows 10 system:
tl.files.load_and_assign_npz(sess=sess, name='name.npz', network=net)
it turn out to be some error, the error seems to be using 'np.load' without specific the encoding parameter  in the file "tensorlayer/files.py", and the error like the following:
"UnicodeError: Unpickling a python object failed: UnicodeDecodeError('ascii', ……)
You may need to pass the encoding= option to numpy.load"

**Comment by CConstance** [comment]
I met this error earlier before. To solve this problem, you may need to pass a parameter to ```np.load()``` function.

It should be changed to ```np.load(encoding='latin1')```
I think the function you mentioned is in ```tensorlayer/files.py```
