### ISSUE TITLE
tensorlayer.layers.AtrousConv2dLayer问题

### ISSUE THREAD

**Issue by Windaway** [tensorlayer/tensorlayer#269]
默认act = None,
但实际如果是这样不设置的话会出错，应该和其他一样默认 tf.identity，或者不添加就
    if act is None:
        act = tf.identity

**Comment by Windaway** [comment]
这个主要是print时候的问题。

**Comment by zsdonghao** [comment]
Thank you for reporting this, I just fixed it here https://github.com/tensorlayer/tensorlayer/commit/3beebb9c0dd67dc07cc137912a2f714c87d07ed8

Best wishes,
Hao
