### ISSUE TITLE
Error in deconv2d_bilinear_upsampling_initializer

### ISSUE THREAD

**Issue by zhimingluo** [tensorlayer/tensorlayer#271]
np.zeros([filter_size, filter_size], dtype=D_TYPE)

will cause type error in Numpy, but the previous dtype=np.float32 works fine

**Comment by zsdonghao** [comment]
Thanks for reporting this, I just fixed it by using previous np.float32 in master branch

**Comment by zsdonghao** [comment]
check this commit https://github.com/tensorlayer/tensorlayer/commit/abc99e77e295ea3a1124b7bd313145115994a266
