### ISSUE TITLE
Should `BiRNNLayer` support different `cell_fn` for fw and dw?

### ISSUE THREAD

**Issue by imhuay** [tensorlayer/tensorlayer#278]
I see the Tensorflow also has a `tf.nn.static_bidirectional_rnn()` and it use different cell for fw and dw.
I just want to know if there are other reason that TL use the same cell.

**Comment by zsdonghao** [comment]
Hi, thanks. we can modify `BiRNNLayer` to support different `cell_fn` for fw and dw, if it is common in practice.
