### ISSUE TITLE
Documentation Update - tl.layers.clear_layers_name()

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorlayer/tensorlayer#289]
Dear Tensorlayers,

I would like first of all to thank you for this outstanding work. Really helped a lot.

It took me two days of work to diagnose a problem I had.
I tried resetting the current graph and trying to redefining it, nothing I was doing was working until I found this function hidden in the tensorlayer library: `tl.layers.clear_layers_name()`.

Maybe, `tl.layers.clear_layers_name()` automatically triggered when the default graph is changed, at least it should be mentioned and highlighted in the documentation. I really wasted many hours trying to figure this out.

**Comment by zsdonghao** [comment]
Thank you for your advise, I will update it now, please let me know or submit a PR if you find my edition is not good enough. 

BTW, https://github.com/tensorlayer/tensorlayer/issues/214 this issue may also helpful for you

**Comment by DEKHTIARJonathan** [comment]
Seems good enough, maybe you should modify the raise error: 

I will open a PR with a change "proposal" for the error raised:

**Current Exception:**
```text
Exception: Layer 'my_layer_name' already exists, please choice other 'name' or reuse this layer
Hint : Use different name for different 'Layer' (The name is used to control parameter sharing)
```

**Proposed Exception:**
```text
Exception: Layer 'my_layer_name' already exists, please choice other 'name' or reuse this layer
Hint : Use different name for different 'Layer' (The name is used to control parameter sharing)
Additional Informations: http://tensorlayer.readthedocs.io/en/latest/modules/layers.html?highlight=clear_layers_name#tensorlayer.layers.clear_layers_name
```
