### ISSUE TITLE
Object Extraction after detection

### ISSUE THREAD

**Issue by alokgrover88** [tensorlayer/tensorlayer#293]
Hi, 

Could you please share a script to extract co-ordinates of the detected classes? I want to extract the objects out of the picture?

**Comment by zsdonghao** [comment]
Hi, if you want to crop the sub-image out of the image, you can use the `tl.prepro.crop`. For visualization, you can use `tl.vis.draw_boxes_and_labels_to_image`.

**Comment by alokgrover88** [comment]
How do I do it based on a specific class?

**Comment by alokgrover88** [comment]
Can any help me with the code? I want to crop out multiple detected objects in an image and store them as separate images?

**Comment by wagamamaz** [comment]
@alokgrover88 try `tl.vis`, actually you can implement it yourself by using libraries like `matplotlib`
