### ISSUE TITLE
Incorrect BiDynamicRNNLayer multilayer implementation

### ISSUE THREAD

**Issue by matthew-z** [tensorlayer/tensorlayer#294]
`bidirectional_dynamic_rnn` +` MultiRNNCell`  will result in incorrect result if num_layers>1.

>  The combined forward and backward layer outputs are used as input of the next layer. tf.bidirectional_rnn does not allow to share forward and backward information between layers.

It is better to use `tf.contrib.rnn.stack_bidirectional_dynamic_rnn `to implement it.

**Comment by zsdonghao** [comment]
hi @matthew-z , do you have any hint to implement dropout with [tf.contrib.rnn.stack_bidirectional_dynamic_rnn](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/stack_bidirectional_dynamic_rnn) ?
