### ISSUE TITLE
set name automatically?

### ISSUE THREAD

**Issue by youkaichao** [tensorlayer/tensorlayer#296]
Currently, I must specify the names of each layer, i.e, when I want to use two dense layer, I have to name them 'dense1' and 'dense2'.

But in tensorflow.contrib.layers, it is ok to have two dense layers without specify their names.

Can it be done in tensorlayer?

**Comment by wagamamaz** [comment]
Set name automatically can help users to build layer quick in many case, but may easily led to fault reuse in some case. I think the library can provide a global setting like `tl.layers.auto_name(True)` to enable this kind of feature? 

Simply disable one `if` statement in `Layer` class and set a new name.
