### ISSUE TITLE
biases shape when data_format='NCHW'

### ISSUE THREAD

**Issue by auroua** [tensorlayer/tensorlayer#297]
I found that the `Conv2dLayer` can not work correctly when set the `data_format='NCHW'` and `b_init is not None`. I also found the `PReluLayer` can not work correctly when the input `data_format='NCHW'`.

**Comment by wagamamaz** [comment]
If I am correct, the author want everyone use the default shape format of TensorFlow, because it can run faster.

**Comment by luomai** [comment]
@zsdonghao
