### ISSUE TITLE
why should we specify input and output shape of DeConv2dLayer?

### ISSUE THREAD

**Issue by youkaichao** [tensorlayer/tensorlayer#298]
I think we only need to supply filter size and stride size and number of filters.

-1 is not supported in this layer, it is annoying.

And if I use DeConv2d, the output shape is not defined (it is ?), which makes the consecutive operation troublesome.

Why not just use `tf.contrib.layers.conv2d_transpose` ?

**Comment by zsdonghao** [comment]
Mark as TODO, [tf.contrib.layers.conv2d_transpose](https://www.tensorflow.org/api_docs/python/tf/contrib/layers/conv2d_transpose) don't support old version of TF. 
As suggest we can update `DeConv2d` by using [tf.contrib.layers.conv2d_transpose](https://www.tensorflow.org/api_docs/python/tf/contrib/layers/conv2d_transpose), then when users are using new version of TF, TL can use it directly.

**Comment by zsdonghao** [comment]
@youkaichao hi, please check this commit https://github.com/tensorlayer/tensorlayer/commit/980e148d7541da9a3ef7b04a1d1e68a1df8caa05

**Comment by youkaichao** [comment]
seems good.  no problems found yet.
