### ISSUE TITLE
DynamicRNN Code Confusion

### ISSUE THREAD

**Issue by wugh** [tensorlayer/tensorlayer#301]
The code in `layers.py` around line number 5438.
```
        if dropout:
            self.cell = DropoutWrapper_fn(self.cell, input_keep_prob=1.0, output_keep_prob=out_keep_prob)
```

Why Dropout Wrapper the self.cell (the self.cell is already wrap by dropout) again. I think we should delete this line.

**Comment by zsdonghao** [comment]
yes, you are right, this line is useless

**Comment by wugh** [comment]
Hi @zsdonghao , I just create a new [pull request](https://github.com/tensorlayer/tensorlayer/pull/302) to delete this two line. 

There also some confusion about the function params, why use the dropout as keep_prob, I think we should make the argument name more sensible. We can create another argument name `keep_prob` here and recommend user not to use the `dropout` params.
