### ISSUE TITLE
can't use checkpoint when use DistributedSession

### ISSUE THREAD

**Issue by ning180** [tensorlayer/tensorlayer#304]
I can't use checkpoint_dir param when use DistributedSession.
RuntimeError "Global step should be created to use StepCounterHook"

the code like:
`with tl.distributed.DistributedSession(task_spec=task_spec,checkpoint_dir="checkpoint",save_checkpoint_secs=1000,save_summaries_steps=100,save_summaries_secs=None) as sess:`

**Comment by lgarithm** [comment]
I think this is because `global_step` was not specified on the optimizer, a possible solution would be like:
```
-    train_op = tf.train.AdamOptimizer(learning_rate=0.0001
-                        ).minimize(cost, var_list=train_params)
+    optimizer = tf.train.AdamOptimizer(learning_rate=0.0001)
+    train_op = optimizer.minimize(cost, var_list=train_params, global_step=tf.train.get_or_create_global_step())

```

**Comment by luomai** [comment]
@ning180 any update? if not, we are going to close this issue.
