### ISSUE TITLE
[Feature Request] - Verbose option for the Layer API

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorlayer/tensorlayer#306]
Hello dear friends,

I have used TL for quite a while and I'm really thankful for all the amazing work.

One thing which appeared very cool to me from the beginning was the verbose graph definition which helped me a lot during debug and development. However, I figured out a bit later that are no way to deactivate the followings:

```shell
  [TL] InputLayer  encoder/input: (?, 256, 256, 1)
  [TL] Conv2dLayer encoder/h1/conv2d: shape:[5, 5, 1, 64] strides:[1, 2, 2, 1] pad:VALID act:identity
  [TL] BatchNormLayer encoder/h1/batch_norm: decay:0.900000 epsilon:0.000010 act:identity is_train:True
```

It is a really interesting feature to have these information, however it could rapidly clutter the console output. 

#### Feature Request

The idea would be to make this output optional (default = True or False). I think there could be different ways to do this.

##### 1. Solution - Create a **verbose** parameter in the Layer API
Simple and backward compatible, a "verbose" parameter can be added to the Layer Class and influence the behavior of [print_params()](https://github.com/tensorlayer/tensorlayer/blob/master/tensorlayer/layers.py#L321) method.

##### 2. Use the Logging module from TF.

Why should we re-invent the wheel ? Everything is already implemented in Tensorflow.
We can use the logging level already existing in TF.

```python
tf.logging._level_names    ## outputs => {50: 'FATAL', 40: 'ERROR', 30: 'WARN', 20: 'INFO', 10: 'DEBUG'}
tf.logging.get_verbosity() ## outputs => 30 (default value)

tf.logging.set_verbosity(tf.logging.DEBUG)
tf.logging.get_verbosity() ## outputs => 10
```

We could for instance determine that for logging level <= 20 (INFO & DEBUG), we normally output the Tensorlayer informations, and we don't perform this action for any higher value.

All the best,

Jonathan

**Comment by zsdonghao** [comment]
Hi, @DEKHTIARJonathan thank you for your suggestion.

- @luomai @lgarithm and me just have a discussion,  we will change all `print` to `logging`, just like this issues https://github.com/tensorlayer/tensorlayer/issues/207 discuss.

- An alternative way to print parameters is``tl.layers.get_variables_with_name``, which allow users to print and get the specific parameters.

**Comment by DEKHTIARJonathan** [comment]
No problem, I close this issue.
