### ISSUE TITLE
add contribution guideline

### ISSUE THREAD

**Issue by lgarithm** [tensorlayer/tensorlayer#318]
Add CONTRIBUTING.md as suggested by https://github.com/tensorlayer/tensorlayer/community.
It should define coding style, doc style, and describe tools that we use to enforce them.

**Comment by lgarithm** [comment]
Currently we've used 
* yapf (format code)
* isort (sort imports)
* autoflake (remove unused imports)

and we should also use
* pylint
when most lints warnings are fixed

**Comment by luomai** [comment]
This is actually very necessary for us. Lets do it.
