### ISSUE TITLE
improve layers folder organization

### ISSUE THREAD

**Issue by luomai** [tensorlayer/tensorlayer#319]
1. place all lambda related layers (tfslim, tflambda ..) into a single lambda.py.
2. we shall not use a deprecated.py to hold deprecated layer. Instead we should use the "@deprecated" decorator shown here: https://stackoverflow.com/questions/2536307/decorators-in-the-python-standard-lib-deprecated-specifically

**Comment by luomai** [comment]
@lgarithm @zsdonghao

**Comment by lgarithm** [comment]
tensorflow provided one:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/util/deprecation.py#L200
