### ISSUE TITLE
deformable conv2d missing function

### ISSUE THREAD

**Issue by zsdonghao** [tensorlayer/tensorlayer#337]
https://github.com/tensorlayer/tensorlayer/pull/234

**Comment by vyokky** [comment]
Sorry I miss these functions in the code:

def tf_flatten(a):
    """Flatten tensor"""
    return tf.reshape(a, [-1])

def _get_vals_by_coords(inputs, coords, idx, out_shape):
    indices = tf.stack([
        idx, tf_flatten(coords[:, :, :, :, 0]), tf_flatten(coords[:, :, :, :, 1])
    ], axis=-1)
    vals = tf.gather_nd(inputs, indices)
    vals = tf.reshape(vals, out_shape)
    return vals

**Comment by zsdonghao** [comment]
cool done..
