### ISSUE TITLE
🚀🚀  Support network architecture that can be easily use

### ISSUE THREAD

**Issue by auroua** [tensorlayer/tensorlayer#367]
Could you support the network architecture like `vgg`, `resnet` easily to use. If I want to use `resnet` in `Pytorch`, I only need to write the following two lines code:
```Python
from torchvision import models
model_ft = models.resnet18(pretrained=True)
```
But in `tensorlayer`, I have to define the network architecture by myself and then load the pretrained parameters.

**Comment by zsdonghao** [comment]
Hi, TL provides' [SlimNetsLayer](http://tensorlayer.readthedocs.io/en/latest/modules/layers.html#connect-tf-slim) that can use all Google TF-Slim's pre-tained model [here](https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models). This is an example for Inception V3 ([click](https://github.com/tensorlayer/tensorlayer/blob/master/example/tutorial_inceptionV3_tfslim.py))

**Comment by zsdonghao** [comment]
@luomai @lgarithm 

I am thinking to release an API that help people import any type of model without knowing anything about slim or other resources.

Something like:

- Get the whole model:
```python
>>> net = tl.model.get_model("inceptionv3", last_layer=True)
>>. print(net.input_placeholder) # <-- where to feed the data in.
... (None, 299, 299, 3)
```

- Get just a part of the model:
```python
>>> net = tl.model.get_model("inceptionv3", layer_name="conv3_2")
```

Any idea about how to design the API ?

**Comment by lgarithm** [comment]
Shall we also provide the following syntax sugar if it is possible to do so in python?
```python
net = tl.models["inceptionv3"][:-1]
net = tl.models["inceptionv3"]["conv3_2"]
```

**Comment by zsdonghao** [comment]
@lgarithm good idea~

**Comment by auroua** [comment]
I have implemented `Resent` in `tensorlayer` which can be created  by 
```Python
nets = get_resnet(x, 1000, 50, sess)
```
The code can load the `tf-slim` pre-trained `ckpt file`, but I found the inference results have some differences with the `tf-slim` model.
The code can be found [here](https://github.com/auroua/InsightFace_TF/blob/master/nets/resnet.py).

**Comment by luomai** [comment]
@zsdonghao The model API can allow model specific parameter as follows:

`net = tl.models.incepvtionv3(**args) # import a inception v3 model with args`

In addition, the API shall also allow "partially reusing the model" for transfer learning, for example.

``net = tl.models.incepvtionv3(**args)[:-1] . # reuse the v3 model and remove the last layer`

**Comment by lgarithm** [comment]
#451

**Comment by zsdonghao** [comment]
# Usage examples for image classification models

## Classify ImageNet classes with VGG16
```python
x = tf.placeholder(tf.float32, [None, 224, 224, 3])

# get the whole model
vgg = tl.models.VGG16(x)

# restore pre-trained VGG parameters
vgg.restore_params()

# use pre-trained VGG
softmax = tf.nn.softmax(vgg.outputs)
...
```

## Extract features with VGG16 and Train a classifier with 100 classes

```python
x = tf.placeholder(tf.float32, [None, 224, 224, 3])

# get VGG without the last layer
vgg = tl.models.VGG16(x, end_with=‘fc2_relu’)

# add one more layer
network = tl.layers.DenseLayer(vgg, 100, name=‘out’)

# initialize all parameters
tl.layers.initialize_global_variables(sess)

# restore pre-trained VGG parameters
vgg.restore_params()

# train your own classifier (only update the last layer)
train_parames = tl.layers.get_variable_with_name(‘out’) 
…
```

## Reuse model

```python
x1 = tf.placeholder(tf.float32, [None, 224, 224, 3])

x2 = tf.placeholder(tf.float32, [None, 224, 224, 3])

vgg1 = tl.models.VGG16(x, end_with=‘fc2_relu’)

# reuse parameters of vgg1, but use different input
vgg2 = tl.models.VGG16(x, end_with=‘fc2_relu’, reuse=True)

# restore pre-trained VGG parameters (as they share parameters, don’t need to restore vgg2)
vgg1.restore_params()
```

**Comment by zsdonghao** [comment]
### About other well-known models

TensorLayer already have some implementations, just wrap them up!

- Vgg19 : https://github.com/tensorlayer/tensorlayer/blob/master/example/tutorial_vgg19.py
- SqueezeNet : https://github.com/tensorlayer/tensorlayer/blob/master/example/tutorial_squeezenet.py
- MobileNet : https://github.com/tensorlayer/tensorlayer/blob/master/example/tutorial_mobilenet.py
- InceptionV3 using TF-Slim : https://github.com/tensorlayer/tensorlayer/blob/master/example/tutorial_inceptionV3_tfslim.py

then provide examples in documentation, and `tutorial_models_xxx.py` in [here](https://github.com/tensorlayer/tensorlayer/tree/master/example)

**Comment by zsdonghao** [comment]
https://github.com/tensorlayer/tensorlayer/issues/394

**Comment by lgarithm** [comment]
what kind of data format will be used for TL graph?

**Comment by lgarithm** [comment]
We might need to use [pickle](https://docs.python.org/3/library/pickle.html) if we want to restore the network from saved file.

**Comment by zsdonghao** [comment]
### Release `tl.models.SqueezeNetV1` which uses `ConcatLayer` @lgarithm

**Comment by zsdonghao** [comment]
### Release MobileNetV1 Model
https://github.com/tensorlayer/tensorlayer/pull/465 `tl.models.MobileNetV1` which uses `DepthwiseConv2d` @lgarithm

**Comment by zsdonghao** [comment]
### Reference Slim Endpoint
`final_endpoint` https://github.com/tensorflow/models/blob/master/research/slim/nets/inception_resnet_v2.py#L125

**Comment by zsdonghao** [comment]
hi, I close this issue, feel free to reopen it if you want to discuss.
