### ISSUE TITLE
Do we have a slack channel?

### ISSUE THREAD

**Issue by hanm** [tensorlayer/tensorlayer#370]
Hello,

The [gitter chat room](https://gitter.im/tensorlayer/Lobby#?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) has two expired slack invitation links. Do we still use Slack, if not what is the preferred communication channel for discussing usage and development (e.g. roadmap, feature proposals)? Thanks!

**Comment by zsdonghao** [comment]
Yes we do, https://join.slack.com/t/tensorlayer/shared_invite/enQtMjUyMjczMzU2Njg4LWI0MWU0MDFkOWY2YjQ4YjVhMzI5M2VlZmE4YTNhNGY1NjZhMzUwMmQ2MTc0YWRjMjQzMjdjMTg2MWQ2ZWJhYzc

However, we suggest to use issues to discuss bug

**Comment by hanm** [comment]
Thanks for the info @zsdonghao. Closing the issue.
