### ISSUE TITLE
If initializer is a constant, do not specify shape.

### ISSUE THREAD

**Issue by youkaichao** [tensorlayer/tensorlayer#373]
if i want to control the weight to be initialized by a constant, W_init arg in many layers(like DenseLayer) will report error:

`If initializer is a constant, do not specify shape.`

**Comment by zsdonghao** [comment]
pls put your code here

**Comment by youkaichao** [comment]
e.g.

```
a = tf.placeholder(dtype=tf.float32, shape=[10, 100])
a = InputLayer(a)
b = DenseLayer(a, W_init=tf.constant(value=1.0, dtype=tf.float32, shape=(100, 100)))
```

**Comment by zsdonghao** [comment]
@youkaichao TL will automatically compute the shape of the parameters, so you don't need to specify the shape.

Please, use `tf.constant_initializer(value=1.0)` instead of `tf.constant()`.

```python
x = tf.placeholder("float32", [None, 100])
n = tl.layers.InputLayer(x, name='in')
n = tl.layers.DenseLayer(n, 80, W_init=tf.constant_initializer(value=1.0), name='d1')
```

**Comment by zsdonghao** [comment]
if my answer solve your question, please close this issue, many thanks.

**Comment by youkaichao** [comment]
@zsdonghao your answer only works when i want the matrix to be initialized by a single number. What if I want to initialize a matrix to be eye matrix?

**Comment by zsdonghao** [comment]
you will need an initializer for it them. btw, what situation make you to initialise an eye matrix?

**Comment by youkaichao** [comment]
sometimes eye matrix is a good initialization which can speed up training

**Comment by zsdonghao** [comment]
i come out with 2 solutions.

1) find the TF initializer for your requirement.
2) customize a layer like that:

```python
class MyDenseLayer(Layer):
  def __init__(
      self,
      layer = None,
      n_units = 100,
      act = tf.nn.relu,
      name ='simple_dense',
  ):
      # check layer name (fixed)
      Layer.__init__(self, layer, name=name)

      # the input of this layer is the output of previous layer (fixed)
      self.inputs = layer.outputs

      # print out info (customized)
      print("  MyDenseLayer %s: %d, %s" % (self.name, n_units, act))

      # operation (customized)
      n_in = int(self.inputs._shape[-1])
      with tf.variable_scope(name) as vs:
          # create new parameters
          W = tf.get_variable(name='W', shape=(n_in, n_units))   <--- you may want to change this part
          b = tf.get_variable(name='b', shape=(n_units))
          # tensor operation
          self.outputs = act(tf.matmul(self.inputs, W) + b)

      # update layer (customized)
      self.all_layers.extend( [self.outputs] )
      self.all_params.extend( [W, b] )
```

**Comment by youkaichao** [comment]
@zsdonghao after scanning the code of tensorflow, i come up with this solution:

```
if W_init is not None and not callable(W_init ):
    #this means initializing with specified shape, so we should get weight without specify shape
else:
    # get weight with shape
```

I recommend that you update this into tensorlayer ^_^

**Comment by DEKHTIARJonathan** [comment]
Shall we open a PR related to this topic ? If no, please close the issue @zsdonghao

**Comment by zsdonghao** [comment]
@youkaichao @DEKHTIARJonathan Just saw this message, @youkaichao I simplify your code as follow, however, I am wondering how could we pass the SHAPE arg into the API?

```python
W = (tf.get_variable(name='W', shape=(n_in, n_units)) if W_init is not None and not callable(W_init ) else tf.get_variable(name='W', shape=SHAPE))
```

**Comment by youkaichao** [comment]
@zsdonghao I can't get it. what do you mean by " I am wondering how could we pass the SHAPE arg into the API" ? which API, tensorlayer API or tensorflow API? "we" means tensorlayer contributor or tensorlayer user?

**Comment by zsdonghao** [comment]
@youkaichao Let me rewrite my sentence.. How could the tensorlayer user pass the SHAPE arg into the TensorLayer API?

**Comment by youkaichao** [comment]
sorry for the delay

I think the code should be:

`
W = (tf.get_variable(name='W', initializer=W_init) if W_init is not None and not callable(W_init) else tf.get_variable(name='W', shape=SHAPE, initializer=W_init))
`

if `W_init is not None and not callable(W_init ) `, then the shape argument can be ignored.

**Comment by zsdonghao** [comment]
feel free to reopen if you want to discuss
