### ISSUE TITLE
取特定大小tensor?

### ISSUE THREAD

**Issue by a258sa258s** [tensorlayer/tensorlayer#374]
現有API似乎沒辦法把前一層layer的output tensor取特定大小出來
ex:
network = tl.layers.MeanPool2d(network, filter_size=(2, 2), padding='SAME')
class_probs = tl.layers.ReshapeLayer(network[:, 0:9], [-1, 3, 3, 10])

result:
TypeError: 'PoolLayer' object is not subscriptable

**Comment by zsdonghao** [comment]
With the master version of TL, given the following model:
```python
>>> x = tf.placeholder("float32", [None, 100])
>>> n = tl.layers.InputLayer(x, name='in')
>>> n = tl.layers.DenseLayer(n, 80, name='d1')
>>> n = tl.layers.DenseLayer(n, 80, name='d2')
>>> print(n)
... Last layer is: DenseLayer (d2) [None, 80]
```

The outputs can be sliced as follow:
```python
>>> n2 = n[:30]
>>> print(n2)
... Last layer is: Layer (d2) [None, 30]
```

The outputs of all layers can be iterated as follow:
```python
>>> for l in n:
>>>    print(l)
... Tensor("d1/Identity:0", shape=(?, 80), dtype=float32)
... Tensor("d2/Identity:0", shape=(?, 80), dtype=float32)
```
