### ISSUE TITLE
[Discussion] Model module and the database management system

### ISSUE THREAD

**Issue by hanm** [tensorlayer/tensorlayer#380]
I really like the idea of having a database backend serving as a model management module. I believe that will automate a lot time consuming tasks related to model management and training. I am trying to evaluate the existing mongo based implementation (db.py), however I find we don't have any documentations and tutorials on how to use the db module. Is it because the db module is still in experimental stage? Should we add documents and tutorial on how to use the db module?

Another idea is to introduce a generic DB interface and support multiple database backends and blob store implementations such as AWS dynamo / S3 in addition to mongo / gridfs. That will make the module more extensible for those who don't want to use mongo and/or have already have their own storage backends (my use case is latter). Any ideas / comments about this?

**Comment by luomai** [comment]
Yes, this is actually on our plan. 

The current db.py is going to under a big refactoring. That is why we have taken its document and code offline and only keep the copy in the repo for future reference.

The refactoring plan aims to achieve the following goals:
- Developing a general DB interface that contains model table schema and dataset table schema. The schema can be actually implemented by any SQL-compatible backend. We are thinking implementing **sqlite** as the first storage and queryable backend.
- As the storage and query relies on general SQL database schema, then we can naturally relies on Cloud provider to provide the database backend for us.

**Comment by hanm** [comment]
Great to hear that's on the roadmap! Starting from sqlite sounds a good idea as it's relatively simple and self contained from operation's perspective.

I am definitely interested on working in this area as well.

**Comment by zsdonghao** [comment]
similar discussion #367

**Comment by lgarithm** [comment]
#451
