### ISSUE TITLE
Strange Implementation Of Word2vecEmbeddingInputlayer.normalized_embeddings

### ISSUE THREAD

**Issue by huntzhan** [tensorlayer/tensorlayer#384]
https://github.com/tensorlayer/tensorlayer/blob/ac9304bfb28abac37efb9f56005eb9051eb69ba9/tensorlayer/layers/core.py#L667

So this normalizes only the `axis=1` dimension. Am I missing something?

**Comment by zsdonghao** [comment]
@huntzhan hi, what is your question?

**Comment by huntzhan** [comment]
Sorry for the noise, I got confused about the axis definition of TF previously.
