### ISSUE TITLE
load_cifar10_dataset fail

### ISSUE THREAD

**Issue by bigtreeljc** [tensorlayer/tensorlayer#420]
如cifar10, text8

**Comment by zsdonghao** [comment]
try vpn?

**Comment by bigtreeljc** [comment]
________________________________________

**Comment by bigtreeljc** [comment]
I use breakwall pptp, But I still can't download them. Is there another way? Maybe someone can make it available in the project?

**Comment by luomai** [comment]
We are aware of these downloading issues in mainland China. However, we don't have extra budget to buy resource to host dataset mirrors in China, e.g., Ali Cloud.

**Comment by lgarithm** [comment]
@luomai, I think we can create mirrors of TL repo in coding.net, gitee.net, etc, and put some small datasets as project attachment.

**Comment by luomai** [comment]
Does coding.net or gitee.com have stable and fast connection within China?

**Comment by bigtreeljc** [comment]
Coding is pretty fast in China and people can use git to push/pull their code. We use it inside our company.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
发件人: Luo Mai <notifications@github.com>
发送时间: Thursday, March 22, 2018 5:59:47 PM
收件人: tensorlayer/tensorlayer
抄送: Junchen; Author
主题: Re: [tensorlayer/tensorlayer] 中国广东东莞这里无法下载多个数据集 (#420)


Does coding.net or gitee.com have stable and fast connection within China?

―

**Comment by shinianzhihou** [comment]
cannot import the cifar10
![image](https://user-images.githubusercontent.com/29772895/44954304-ac301e80-aed2-11e8-9927-8e8847e53c2e.png)

**Comment by zsdonghao** [comment]
fixed by 2.0.0 version
