### ISSUE TITLE
DeConv3d error

### ISSUE THREAD

**Issue by lsmale** [tensorlayer/tensorlayer#455]
I am using DeConv3d in tensorlayer.layers, but I got the error that missing argument as follows: `convolution3d_transpose() missing 1 required positional argument: 'inputs'`.
And my tensorlayer version is 1.8.0, tensorflow version is 1.6.0.

**Comment by zsdonghao** [comment]
hi, this is a bug due to a recent update.. I am fixing it now, it will be done in few minutes.
