### ISSUE TITLE
introduce a canonical data dir

### ISSUE THREAD

**Issue by lgarithm** [tensorlayer/tensorlayer#460]
Currently when we clone a new tensorlayer repo and run some tutorials, TL will download the data/weights and save them in the current directory. If we run commands like `git clean -fdx`, the data will be lost. If we have two TL repos on the same computer (not sure if this is a common case for many users), the data can't be shared.
I think we can store all the data/weight files in a directory called `DATA_DIR`, it is located at a fix path on a computer, e.g. `~/var/tensorlayer`, `~/.tensorlayer` (can be controlled by an environment variable), and we could organise the well known files as:

```
# DATA_DIR/data/<dataset-name>/<file>
# DATA_DIR/models/<model-name>/<file>
DATA_DIR/
   data/
      mnist/
         t10k-images-idx3-ubyte.gz
         ...
      cifat/
        cifar-10-binary.tar.gz
        ...
   models/
      vgg/
         vgg16_weights.npz
         vgg19_weights.npz
         ...
      yolo/
       
```

**Comment by zsdonghao** [comment]
Hi, all `tl.files.load_xxx_dataset` APIs have an argument `path`, user can set they own path if they want 2 tensorlayer code use the same data.

http://tensorlayer.readthedocs.io/en/latest/modules/files.html#mnist
