### ISSUE TITLE
Why do not add W b of DropconnectDenselayer to all_params?  

### ISSUE THREAD

**Issue by liudragonfly** [tensorlayer/tensorlayer#466]
When I use DropconnectDenselayer  to construct a MLP network, it can not be trained as the W b of DropconnectDenselayer  are not added to all_params. Besides, enable/disable noise layers do not work.

**Comment by zsdonghao** [comment]
Thank you for reporting this bug, I will fixed it in this PR https://github.com/tensorlayer/tensorlayer/pull/467/commits/3825e6c8a6d8fff0a1bdee0bb6ca313696761a84 , so you can fix the bug by reinstalling TL in 10 mins.
