### ISSUE TITLE
Is there a proper way to add learnable activation functions to convolution layers?

### ISSUE THREAD

**Issue by mohammadul** [tensorlayer/tensorlayer#471]
Suppose I have a custom activation function `cust_act()` that has a parameter `alpha` that is learnable. Now I want to apply it to a convolution layer as below:
`y = Conv2d(x, 1, ..., act=cust_act)`

I see that the parameter `alpha` does not add to the `y.all_params` list and remains hidden only inside tensorflow. In this case, what is the most straight-forward approach to get the thing correct and complete?

It seems that this feature is not available in the tensorlayer properly. I see that this is happening due to lots of inconsistent coding in the `convolution.py` file.

In `conv2d()` function, earlier in 1.8.3rc0 version, there was 
` new_variables = tf.get_collection(TF_GRAPHKEYS_VARIABLES, scope=vs.name)`

but, now it is changed to
` new_variables = conv2d.weights`

On the other hand, it is still retained in `deconv2d()` function as
` new_variables = tf.get_collection(TF_GRAPHKEYS_VARIABLES, scope=vs.name)`

So, for
`y = Deconv2d(x, 1, ..., act=cust_act)`,

that the parameter `alpha` does add to the `y.all_params` list in tensorlayer directly from tensorflow routine.

**Comment by zsdonghao** [comment]
Hi, one of the simple way to customize you layer is to use `LambdaLayer`, alternatively, you can write a new layer like `PReluLayer: http://tensorlayer.readthedocs.io/en/latest/_modules/tensorlayer/layers/special_activation.html#PReluLayer

**Comment by mohammadul** [comment]
Thanks.
