### ISSUE TITLE
Why not testing with network trained previously?

### ISSUE THREAD

**Issue by serieslover** [tensorlayer/tensorlayer#472]
when running with program "tutorial_generate_text.py" in the document examples of Natural language processing, i found it's testing with another network, not the one just trained, just as below

    # Inference for Training
    network, lstm1 = inference(input_data, is_train=True, sequence_length=sequence_length, reuse=None)
    # Inference for generate text, sequence_length=1
    network_test, lstm1_test = inference(input_data_test, is_train=False, sequence_length=1, reuse=True)
  
    Is there a mistake, or just a misunderstanding of me? Thanks very much for an answer

**Comment by zsdonghao** [comment]
you are right, it loads different network, if you want to load the network you just trained. 
you can add `tl.files.load_and_assign_npz` in the training code.

**Comment by zsdonghao** [comment]
The `reuse=True` means we use the same network, this is how TF static graph reuses a network.

I close this issue, feel free to reopen it if you want to discuss.
