### ISSUE TITLE
bug in nlp.py

### ISSUE THREAD

**Issue by liudragonfly** [tensorlayer/tensorlayer#475]
line 561
raw: ids = [word2id.get(w.strip()) for w in words]
In Python3, w is bytes, it should be converted to string.
ids = [word2id.get(w.decode().strip()) for w in words] works.

**Comment by zsdonghao** [comment]
hi, could you create a push request for it?

**Comment by liudragonfly** [comment]
I try.

**Comment by wagamamaz** [comment]
Feel free to reopen if you have any other problems.
