### ISSUE TITLE
something wrong in tutorial_word2vec_basic.py

### ISSUE THREAD

**Issue by liudragonfly** [tensorlayer/tensorlayer#476]
self.all_params = [embeddings, nce_weights, nce_biases]

The shape of nce_biases is different from the shape of nce_weights.
As a result, tl.files.save_npz(emb_net.all_params...) throws ValueError.

ValueError: could not broadcast input array from shape(vocabulary_size, embedding_size) into shape(vocabulary_size)

**Comment by DEKHTIARJonathan** [comment]
I confirm this issue, I can reproduce @zsdonghao.

```python
ValueError: could not broadcast input array from shape (50000,128) into shape (50000)
```

Ping @liudragonfly @aMarry

**Comment by DEKHTIARJonathan** [comment]
@zsdonghao how comes ? I can't manage to make this work...
