### ISSUE TITLE
Need help in  tutorial_word2vec_basic.py

### ISSUE THREAD

**Issue by aMarry** [tensorlayer/tensorlayer#478]
I can not save the model with NPZ file. 
with is shown as follows:
  ## could not broadcast input array from shape (50000,128) into shape (50000)

when I run this code :tl.files.save_npz(emb_net.all_params, name=model_name+'.npz')

what's more  i do not konw how to set the label :help wanted  😿

**Comment by DEKHTIARJonathan** [comment]
Duplicate of #476
