### ISSUE TITLE
How to redirect print to a file?

### ISSUE THREAD

**Issue by whiteeat** [tensorlayer/tensorlayer#484]
Normally, if in cmd, I say python main.py --mode=srgan >temp.txt, I should redirect print to temp.txt file. However, when I did this using srgan code, it doesn't take any effect. So probably it is caused by tensorlayer? I've study the code a little bit but haven't get any clues yet. Do you know the reason probably why this happens?

**Comment by DEKHTIARJonathan** [comment]
Try all of the followings:

```shell
python main.py --mode=srgan >temp1.txt
python main.py --mode=srgan &>temp2.txt
python main.py --mode=srgan >>temp3.txt
```

One of these could work ;)

**Comment by whiteeat** [comment]
![image](https://user-images.githubusercontent.com/10330544/38653683-761f9136-3e3e-11e8-9b5e-52799aa78af2.png)

It doesn't work. I'm using Windows 7, cmd.exe

**Comment by whiteeat** [comment]
Actually I tried most of them. I think the root cause is somewhere in the tensorlayer, kind of modifying the default behavior of stream stuff, but I can't figure out how to fix that.

**Comment by DEKHTIARJonathan** [comment]
Did you realise that you accuse people and a library when you don't even understand that this command only apply to Linux-based systems ?
Before saying that something doesn't work and accuse anyone, you should definetely ask the correct question ...

This is not the place to answer your question, not TL related. Please go to stackoverflow.com

**Comment by whiteeat** [comment]
It's my bad not clarifying that I'm using windows sorry (I thought cmd could imply that). But I don't mean accusing anyone, I just want to state my opinion about the potential problems and very likely I'm wrong. (And my first language is not English, so probably I don't use words properly) 

Back to my question, the thing is that, when I write a simple print('Hello') test.py, I open my cmd, then say 'python test.py >temp.txt', I will get a temp.txt and observe 'Hello' is in the temp.txt. However, when I do the same thing using TL. more specifically, using srgan code (though I think srgan code has nothing to do with I/O stream stuff), the program will be seems running, but nothing appears in the temp.txt. 

Actually I have an idea of manually flushing streams after every print, and I'll test it tomorrow.

**Comment by whiteeat** [comment]
In srgan code, I have manually shut down logging library by logging.disable(logging.CRITICAL+1), and the only things appear in the terminal is from print statements. So I guess pure print and logging won't affect each other?

Also, just test the code:
`import logging
logging.disable(logging.CRITICAL+1)
print('hello')`

and I can redirect the print to a file using python test.py >temp.txt

So, disable logging shouldn't have side effect on print statement?

**Comment by DEKHTIARJonathan** [comment]
Come on ... I told you  3 times **This Is Not Related To TL**. I can't be more clear !

This is basic python. Please go to  https://stackoverflow.com/

As you don't want to listen, **I prove it and you close this issue. Please stop this!**

**main.py:**

```python
import logging

logging.debug("I am a debug print")
logging.info("I am an info print")
logging.warning("I am a warning print")
logging.error("I am an error print")
logging.critical("I am a critical print")

print("I am a classical print")
```

Now you launch:

```shell
python main.py > log.txt
```

#### Results

**Console:**
```
WARNING:root:I am a warning print
ERROR:root:I am an error print
CRITICAL:root:I am a critical print
```

**log.txt file:**
```
I am a classical print
```


------------------------

We explain something you don't listen (read). This is NOT TL related => https://stackoverflow.com/

**Comment by whiteeat** [comment]
But in srgan code, the print statement won't appear in log.txt file. That essentially what my problem is.

**Comment by DEKHTIARJonathan** [comment]
I will not answer anymore. You don't listen to me

**Comment by whiteeat** [comment]
Ha, I figure out my problem. I think my guess is partially right and it is not an issue related to TL: normally, Python stdout will only flush by the end of the program or something special event occurs like input (or stream buffer is full I guess). So, I run the srgan train, then it will take long time to finish, and then it creates an illusion that it doesn't work. So using: print('Hello', flush=True) or sys.stdout.flush() after print will make print statement instantly appears in the log file. 

So, the conclusion is, it has nothing to do with TL. I'll close it.
