### ISSUE TITLE
InstanceNormalization OOM

### ISSUE THREAD

**Issue by syan1992** [tensorlayer/tensorlayer#493]
Why OOM happend when I change "BN" to "Instancenorm"?

**Comment by zsdonghao** [comment]
pls, show your code and environment

**Comment by syan1992** [comment]
I run it on nvidia 1080ti with 11G memory. I change the code a little to realize another task. Although my input image size is 700*700, it works when I use 'BN' in the generator and will OOM using instancenorm. I set batchsize=1.

**Comment by zsdonghao** [comment]
can you show your code and the error?

**Comment by wagamamaz** [comment]
if batch size > 1 work, and you set batch size to 1, it should not have OOM problem.

**Comment by wagamamaz** [comment]
Feel free to reopen if you have any other problems.
