### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by degawong** [tensorlayer/tensorlayer#549]
### New Issue Checklist

- [ ]ImportError: No module named progressbar

### Issue Description

 when i use the command pip install -e .,error occurs as 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/dega/Downloads/degawong/tensorflow/tensorlayer/setup.py", line 18, in <module>
        from tensorlayer import (
      File "tensorlayer/__init__.py", line 14, in <module>
        from . import files
      File "tensorlayer/files.py", line 12, in <module>
        import progressbar
    ImportError: No module named progressbar
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/.../tensorflow/tensorlayer/

but if i use import progressbar,it works well and get current screen picture
someone helps me,thanks

### Reproducible Code

- ubuntu 17.10

[INSERT CODE HERE]

```python
pip install -e .

**Comment by DEKHTIARJonathan** [comment]
Are you sure, you have the latest master version?

If you don't need to install from sources, you can use the PyPI package.

`pip install tensorlayer`

Can you give us the output of this command :

`pip freeze`

**Comment by DEKHTIARJonathan** [comment]
I tried a fix, I think to know where the error come from. I will push the PR #550 to master in 2min.
Can you update your library to the latest commit in master ? And try again 👍.

I hope this will solve the issue.

**Comment by DEKHTIARJonathan** [comment]
No answer, I close this issue
