### ISSUE TITLE
A small problem in the maxPool2D initializer

### ISSUE THREAD

**Issue by cdhcs1516** [tensorlayer/tensorlayer#551]
### Issue Description
We run the code of srgan with tensorflow 0.1.1 and tensorlayer 1.8.5, and we meet an error shown as:

  File "/home/deeplearning/.local/lib/python2.7/site-packages/tensorlayer/layers/pooling.py", line 205, in __init__
    raise Exception("len(strides) should be 2.")
Exception: len(strides) should be 2.

Then we go to the implemention of the pooling.py and find some confusion. The Line 248-249 of pooling.py demonstrated as follows:
```python
if len(strides) == 2:
    raise Exception("len(strides) should be 2.")
```
Obviously it is invalid. Maybe it should be:
```python
if len(strides) != 2:
    raise Exception("len(strides) should be 2.")
```

**Comment by DEKHTIARJonathan** [comment]
Tensorflow should be updated to latest version.
How can you hope it is working a version of TF more than 1 year old and the latest version of TL?

**Comment by zsdonghao** [comment]
@cdhcs1516 thank you for reporting this bug, it is due to a previous update.
