### ISSUE TITLE
Create a tutorial to similar to Keras Layers/Modules but with TF-Slim

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorlayer/tensorlayer#552]
Very similar to this file with **Keras**: https://github.com/tensorlayer/tensorlayer/blob/master/example/tutorial_keras.py

We should create the same thing with TF-Slim

**Comment by zsdonghao** [comment]
We have the `SlimNetsLayer` ~ It that what you mean?

**Comment by DEKHTIARJonathan** [comment]
I just mean about creating a small example using it

**Comment by 2wins** [comment]
@DEKHTIARJonathan Please check the PR. Thanks.
