### ISSUE TITLE
choose an issue manage tool and stick to use it

### ISSUE THREAD

**Issue by lgarithm** [tensorlayer/tensorlayer#558]
### New Issue Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/tensorlayer/tensorlayer/issues)

### Issue Description

As tensorlayer grows larger, we need a better issue management system.
After discussed with @DEKHTIARJonathan and @zsdonghao, we decided to choose one tool to do this. Options are:
* github projects 
* https://app.gitkraken.com/

We will try to use them for several weeks and decide which one to choose.

**Comment by zsdonghao** [comment]
I vote `github project`, it can keep the management simple ~

**Comment by DEKHTIARJonathan** [comment]
I would also support Github Projects !

**Comment by DEKHTIARJonathan** [comment]
No one seems to be using GitKraken platform. I close the issue in favor of Github Projects
