### ISSUE TITLE
NCHW issue with Conv2D and Conv2DLayer.

### ISSUE THREAD

**Issue by unclejimbo** [tensorlayer/tensorlayer#561]
### New Issue Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/tensorlayer/tensorlayer/issues)

### Issue Description

These two layers breaks when using "NCHW" format. There is a related issue #297.

In `Conv2dLayer`, you have

```python
class Conv2dLayer(Layer):
    # breaks when using "NCHW" format, should use tf.nn.bias_add instead
    self.outputs = act(tf.nn.conv2d(...) + b)
```

Also in the `Conv2D` wrapper, the dimension order of `strides` is wrong when using the "NCHW" format. See [tf.nn.conv2d](https://www.tensorflow.org/api_docs/python/tf/nn/conv2d).

Plus, the documentation about the `strides` parameter of these two layers are also wrong.

**Comment by 2wins** [comment]
@DEKHTIARJonathan When does one use `deprecated_alias`. Most convolutional layers in tensorlayer had the decorator `@deprecated_alias(layer='prev_layer', end_support_version=1.9)`. [Link](https://github.com/tensorlayer/tensorlayer/blob/master/tensorlayer/layers/convolution.py)
Can I modify the code to support `data_format="NCHW"` or leave it?
Please comment it. Thanks.

**Comment by DEKHTIARJonathan** [comment]
@unclejimbo can you please provide a sample code that I can execute to reproduce the issue ?
Thanks for reporting the issue btw.

@2wins I prefer to first focus on implementing a unittest to reproduce the bug. Then we'll find out how to solve this bug. It doesn't seem `data_format` has been deprecated to me so we'll see how to solve it ;)

**Comment by 2wins** [comment]
@DEKHTIARJonathan I see. BTW could you explain when one can use the deocrator `deprecated_alias`?

**Comment by DEKHTIARJonathan** [comment]
Have a look to my PR: https://github.com/tensorlayer/tensorlayer/pull/480#issuecomment-380924591

**Comment by unclejimbo** [comment]
@DEKHTIARJonathan Okay, I set up a minimal example

```python
import tensorflow as tf
import tensorlayer as tl

x = tf.placeholder(tf.float32, shape=[32, 28, 28, 1])

# [N H W C] -> [N C H W]
x = tf.transpose(x, perm=[0, 3, 1, 2])
print("transposed shape: ", x.shape)

network = tl.layers.InputLayer(x)
network = tl.layers.Conv2dLayer(network, data_format="NCHW")
```

which will give you

> Traceback (most recent call last):
  File "tutorial_mnist.py", line 11, in <module>
    network = tl.layers.Conv2dLayer(network, data_format="NCHW")
  **File "/usr/lib/python3.6/site-packages/tensorlayer/layers/convolution.py", line 207, in __init__
    tf.nn.conv2d(self.inputs, W, strides=strides, padding=padding, use_cudnn_on_gpu=use_cudnn_on_gpu, data_format=data_format) + b)**
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 979, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 297, in add
    "Add", x=x, y=y, name=name)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 28 and 100 for 'cnn_layer/add' (op: 'Add') with input shapes: [32,100,28,28], [100].

Same thing for `Conv2d`.

**Comment by DEKHTIARJonathan** [comment]
I'll have a look ASAP ;)

**Comment by 2wins** [comment]
@DEKHTIARJonathan Can I solve this problem? I have already had a solution for `tl.layers.Conv2d`.
```python
# before
strides = (1, strides[0], strides[1], 1)

# after
if data_format in ['NHWC', 'channels_last']:
    strides = (1, strides[0], strides[1], 1)
elif data_format in ['NCHW', 'channels']:
    strides = (1, 1, strides[0], strides[1])
else:
    raise ValueError("'data_format' should be among 'NHWC', 'channels_last', 'NCHW', 'channels_first'.")
```

**Comment by 2wins** [comment]
@DEKHTIARJonathan Do you know that our many other layers _e.g._ `DeConv2dLayer`, `Conv3dLayer` do NOT support `data_format` even though their corresponding TensorFlow layers do.

**Comment by DEKHTIARJonathan** [comment]
@2wins Absolutely ! Open a PR with [WIP] in the title.
Try to follow the same pattern and rules I have given you in your first PR. In case u need help, just ping me

**Comment by lgarithm** [comment]
btw, tensorflow doesn't support NCHW on CPU machine, there will a runtime error for CPU users
```
UnimplementedError (see above for traceback): Generic conv implementation only supports NHWC tensor format for now.
```

**Comment by zsdonghao** [comment]
fixed
