### ISSUE TITLE
Changelog 1.8.5 is incomplete.

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorlayer/tensorlayer#562]
We have made quite a few changes between the release `1.8.5rc2` and `1.8.5`.
Most of the changes have not been logged.

We also need to add @2wins as a contributor of this release.

I am thinking about finding a way to enforce a policy that each PR should raise a (non-blocking) warning if a file called **Changelog.md** is not modified. What do you think about this @zsdonghao ?

It would become much simpler to handle new releases.

**Comment by lgarithm** [comment]
I like this idea. 
We need to find out if there are free automation bot could help it.

**Comment by DEKHTIARJonathan** [comment]
I have seen something called Danger doing exactly this : https://github.com/danger/danger

**Comment by lgarithm** [comment]
We've discussed a lot about split/reorganise **README.md** and we still don't have **Changelog.md** yet.
@luomai @zsdonghao

**Comment by zsdonghao** [comment]
@lgarithm tensorflow also don't have **Changelog.md**, i think that info can put into release?

**Comment by lgarithm** [comment]
@zsdonghao tensorflow has [RELEASE.md](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md), which serves similar purpose as Changelog.md.

**Comment by DEKHTIARJonathan** [comment]
Fixed in #563
