### ISSUE TITLE
How to save model structure in TensorLayer?  Not only save the parameters of model

### ISSUE THREAD

**Issue by kenjewu** [tensorlayer/tensorlayer#564]
How to save model structure in TensorLayer?  Not only save the parameters of model.

**Comment by DEKHTIARJonathan** [comment]
You have to use the tensorflow saver

**Comment by zsdonghao** [comment]
Apart from tensorflow saver, we are working on a graph API which can save model into caffe-like prototxt file https://github.com/tensorlayer/tensorlayer/pull/469

**Comment by rachitagrawal** [comment]
The issue #469 is closed but looks like saving the model structure option is still not available. Can someone please confirm?

**Comment by zsdonghao** [comment]
we are planing to save model into onnx format

**Comment by rachitagrawal** [comment]
@zsdonghao Thanks Hao. Is there a pre-released version that I can use to save my tensorlayer based model into ONNX format?

**Comment by zsdonghao** [comment]
@rachitagrawal hi, this ONNX function still under development.
before that, you can use TF's saver such as `.pb`.

**Comment by DEKHTIARJonathan** [comment]
@rachitagrawal if you wanna help to implement this functionnality. You are more than welcome in the team ;)

**Comment by zsdonghao** [comment]
I implemented a graph API here https://github.com/tensorlayer/tensorlayer/pull/751

then we can save the architecture and parameters together

**Comment by zsdonghao** [comment]
fixed by 2.0.0 version
