### ISSUE TITLE
Conda Install

### ISSUE THREAD

**Issue by abi-aryan** [tensorlayer/TensorLayer#570]
Would it be a good idea to create a conda install for Tensorlayer?

**Comment by DEKHTIARJonathan** [comment]
It is perfectly installable using `pip` which is the most widespread and commonly used python package management system.

PIP even if you use Anaconda Distributions (I do it everydays). Maybe I'm missing, what would be the advantage ?

**Comment by abi-aryan** [comment]
Yup, the installation was very smooth using pip and it does show under my Conda packages now. 

`conda list`

The reason I mentioned it is pip handles only Python based dependencies whereas conda handles non-python library dependencies as well. It can be essentially helpful for large relational databases. If in future, we plan to extend it to include other implementations it should be a requirement. 

Any dependency that doesn't have a setup.py file in its source file should be hard to integrate. 

Maybe I can start experimenting with it and once we have it, we can eventually decide whether to include it or not? No harm, right?

**Comment by DEKHTIARJonathan** [comment]
I'm not against in any case, however I still struggle to see the added value.

If we decide to provide let's say a GoLang API for tensorlayer. Clearly you will not use anaconda. Same remark for Tensorflow-JS if we decide to provide tensorlayer in javascript.

So what kind of project would benefit of having Anaconda package that can not use at all PyPI. There must be something I don't understand.

Uo to me Anaconda and PyPI basically do the exact same stuff, however conda allows much more complex librairies to be installed. As TL is only developed on top of TF in pure Python... I don't see the benefits.

Even TF which is developed in C++ and heavily use CUDA and CUDNN code do not rely on Conda package manager.

I mean if you want to do it, I'm not against in any case. However, doing such a thing takes some time, I would like to be sure that you are not doing it for nothing
