### ISSUE TITLE
Error caused by using tl.layers.DeformableConv2d function

### ISSUE THREAD

**Issue by Liang-yc** [tensorlayer/tensorlayer#572]
### New Issue Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [ ] I searched for [existing GitHub issues](https://github.com/tensorlayer/tensorlayer/issues)

### Issue Description

An Error caused when using tl.layers.DeformableConv2d.
### Reproducible Code

- Which OS are you using ?
 Windows 7 x64
- Please provide a reproducible code of your issue. Without any reproducible code, you will probably not receive any help.

```python



net = tl.layers.InputLayer(x, name='input_layer')
offset1 = tl.layers.Conv2d(net, 18, (3, 3), (1, 1), act=act, padding='SAME', name='offset1')
net = tl.layers.DeformableConv2d(net, offset1, 32, (3, 3), act=act, name='deformable1')
offset2 = tl.layers.Conv2d(net, 18, (3, 3), (1, 1), act=act, padding='SAME', name='offset2')
net = tl.layers.DeformableConv2d(net, offset2, 64, (3, 3), act=act, name='deformable2')

```
When I used this code provided by [Tensorlayer API documents](http://tensorlayercn.readthedocs.io/zh/latest/modules/layers.html?highlight=deformable#tensorlayer.layers.DeformableConv2d), a TypeError was caused. I found a mistake in [`convolution.py`](https://github.com/tensorlayer/tensorlayer/blob/5dda66397f66f11dff3640ae91a032e5dd5207de/tensorlayer/layers/convolution.py). And I suggest you delete Line 971 in `convolution.py` or do something to fix this error.

**Comment by 2wins** [comment]
As @Liang-yc said, it works well after remove [Line 971](https://github.com/tensorlayer/tensorlayer/blob/master/tensorlayer/layers/convolution.py#L971)

**Comment by DEKHTIARJonathan** [comment]
Alright, I managed to reproduce the problem and I have added it to the test codebase.
https://github.com/tensorlayer/tensorlayer/pull/573

I will try a few fixes ;)
