### ISSUE TITLE
Add a layer that supports lambda expressions for multiple layers

### ISSUE THREAD

**Issue by One-sixth** [tensorlayer/tensorlayer#576]
### New Issue Checklist

- [ ] I have read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [T] I searched for [existing GitHub issues](https://github.com/tensorlayer/tensorlayer/issues)

### Issue Description

Add a new layer. Enter multiple layers as arguments to function operations.
It looks like a combination of ElementwiseLayer and LambdaLayer.
I think it can simplify some operations.

### Reproducible Code

```python

import tensorflow as tf
import tensorlayer as tl

class ElementwiseLambdaLayer(tl.layers.Layer):
    def __init__(
            self,
            layers,
            lambda_fn,
            name='elementwiselambda_layer',
    ):
        super(ElementwiseLambdaLayer, self).__init__(prev_layer=layers, name=name)
        ts = [layer.outputs for layer in layers]
        self.outputs = lambda_fn(*ts)
        self.all_layers.append(self.outputs)

def get_encoder(x, is_train, reuse):
    noise_t = tf.random_normal(tf.stack([tf.shape(x)[0], n_hidden]))
    with tf.variable_scope('encoder', reuse=reuse):
        net = tl.layers.InputLayer(x)
        net = tl.layers.FlattenLayer(net)
        net = tl.layers.DenseLayer(net, 400, tf.nn.elu, name='dense1')
        mean = tl.layers.DenseLayer(net, n_hidden, name='mean')
        std = tl.layers.DenseLayer(net, n_hidden, name='std')
        noise = tl.layers.InputLayer(noise_t, name='noise')
        # mean_t = mean.outputs
        # std_t = std.outputs
        # z = mean_t + noise_t * tf.exp(std_t * 0.5)
        z = ElementwiseLambdaLayer([mean, std, noise], lambda mean, std, noise: mean + noise * tf.exp(std * 0.5))
        return z, mean, std

**Comment by zsdonghao** [comment]
@One-sixth this is a very good feature indeed !

I think you can make a new push request and put your code as example ~

Best wishes.

**Comment by One-sixth** [comment]
@zsdonghao I'm new to github. Can you help modify the code and add this new feature?

**Comment by DEKHTIARJonathan** [comment]
Contribution Guidelines: https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md
Instruction to install the project: https://github.com/tensorlayer/tensorlayer/blob/master/README.md

Beginner Guide: https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by One-sixth** [comment]
I have already submitted pr.
