### ISSUE TITLE
Why do we have: tl.layers.initialize_global_variables

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorlayer/tensorlayer#578]
Why do we have a function which is doing nothing else that `sess.run(tf.global_variables_initializer())`

https://github.com/tensorlayer/tensorlayer/blob/7d9506daf0799d8e8f24c6ab73f480afc52802a8/tensorlayer/layers/core.py#L314

**Comment by zsdonghao** [comment]
Because we want to make TF0.12 and TF1.0+ use the same code.

**Comment by DEKHTIARJonathan** [comment]
The code for TF0.12 has been commented out, so now it's more or less useless right ?

**Comment by zsdonghao** [comment]
yes, but many codes using it already~ and if google update the API name, it can still works~

**Comment by DEKHTIARJonathan** [comment]
As you wish ;)
