### ISSUE TITLE
Implement **Dilated Convolutions** that allows very large receptive fields while only growing the number of parameters logarithmically

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorlayer/tensorlayer#581]
http://www.inference.vc/dilated-convolutions-and-kronecker-factorisation/

**Comment by 2wins** [comment]
Do you want more advanced layer than `tf.nn.atrous_conv2d` ([Link](https://www.tensorflow.org/api_docs/python/tf/nn/atrous_conv2d)) which is a.k.a. dilated convolution?
If so, which function is needed more?

**Comment by DEKHTIARJonathan** [comment]
My bad, I wasn't aware that they were called `atrous_conv2d`
