### ISSUE TITLE
[Feature Request] - Transposed AtrousConv2dLayer

### ISSUE THREAD

**Issue by dengyueyun666** [tensorlayer/tensorlayer#642]
There is AtrousConv2dLayer in Tensorlayer，but the transpose of AtrousConv2dLayer or De-AtrousConv2dLayer？
AtrousConv2dLayer uses tf.nn.atrous_conv2d in source code, why not reimplement a  layer like De-AtrousConv2dLayer that uses tf.nn.atrous_conv2d_transpose?

**Comment by zsdonghao** [comment]
@dengyueyun666 Hi, I suggest to use English here, as many contributors are not Chinese, they can help you as well.

**Comment by DEKHTIARJonathan** [comment]
@dengyueyun666 We would much appreciate a PR on this topic. Would you like to send us a PR on this topic ?

**Comment by DEKHTIARJonathan** [comment]
Closing: https://github.com/tensorlayer/tensorlayer/pull/662
