### ISSUE TITLE
tl.files support file objects

### ISSUE THREAD

**Issue by fangde** [tensorlayer/tensorlayer#653]
### New Issue Checklist
It seems based tf.gfile system, we can directly read and write the  files and data in the cloud.
this could be an valuable feature for people use distributed training.

it would be less confusing with an update of the tf.files to  accept file object rather than just the file names.

The following code is working, actually.
Hope we can refine it 

[INSERT CODE HERE]

```python
# ======================================================== #
###### THIS CODE IS AN EXAMPLE, REPLACE WITH YOUR OWN ######
# ======================================================== #

os.environ['AWS_REGION']='cn-north-1'
with tf.gfile.GFile('s3://models-backup/mytest.npz','r+b') as f:
    tl.files.save_npz(net.all_params,f,sess=sess)
    

# ======================================================== #
###### THIS CODE IS AN EXAMPLE, REPLACE WITH YOUR OWN ######
# ======================================================== #
```

**Comment by fangde** [comment]
the np.savez accept both file object and file name, maybe we can update the docs to highlight this
while it sees loading is notworkinging

**Comment by DEKHTIARJonathan** [comment]
Is it related to the PR #655 you opened ?

**Comment by zsdonghao** [comment]
I close this issue, feel free to reopen it if you want to discuss.
