### ISSUE TITLE
Integrating the source code in the Chinese and English projects.

### ISSUE THREAD

**Issue by luomai** [tensorlayer/tensorlayer#665]
### New Issue Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/tensorlayer/tensorlayer/issues)

### Issue Description

Today, the Chinese and English documentations of TensorLayer are maintained in completely separated repositories, leading to poor management of source codes, duplications of CI tests, and extra maintenance and development works. Shall we considering integrating these two repositories?
What are the best way of maintaining multi-language documentations for TensorLayer.

A deeper question is that: we are having more and more documents in the types of tutorials, examples, blogs, documentations. They can be written in multiple languages. What is the best way to manage all these materials in a single repo?

**Comment by DEKHTIARJonathan** [comment]
We have to be careful I think with the Chinese / English integration. Having both is without a doubt a good opportunity, however if we want to have international adoption  and not focus on China, we need to keep the focus primarily on English and keep English as the main official language.

I would consider Chinese documentation to be important to maintain, however not a primary focus.

You should have a look to git submodule. It is a nice way to synchronize to repositories. In my opinion it would be a very good way to keep the synchronisation through time with minimal effort.

**Comment by luomai** [comment]
If you look into the current Chinese document [repo](https://github.com/tensorlayer/tensorlayer-chinese/tree/master/tensorlayer), it has a full replication of the TensorLayer source code. Maintaining the source code replication is difficult. My proposal is about making the Chinese documentation refer to the main TL repository directly. @zsdonghao and I were looking into it before, but we cannot find a good way of doing that through ReadTheDoc.

**Comment by DEKHTIARJonathan** [comment]
Have a look to git submodule, that's **exactly** what you are looking for

**Comment by zsdonghao** [comment]
if it is easy to combine, we can do it~.

**Comment by lgarithm** [comment]
+1 for gitsubmodule.

**Comment by luomai** [comment]
done.

**Comment by DEKHTIARJonathan** [comment]
@luomai documentation building is failing
