### ISSUE TITLE
 ‘net.print_params()’ and ‘net.print_layers()’ does not work

### ISSUE THREAD

**Issue by JunbinWang** [tensorlayer/tensorlayer#696]
### Issue Description
When I try to run the 'tutorial_mnist.py' example from the tutorial website today, I found these two functions don't work ( ‘net.print_params()’ and ‘net.print_layers()’ ) . They don't print anything.

### Reproducible Code

The code I used is from: [here](https://github.com/tensorlayer/tensorlayer/blob/ed68215ecd84c13911d911b463b661ffd0cc6e1e/example/tutorial_mnist_simple.py)  

I try this code on both Mac and Linux system. With python 3.0 and latest tensorflow and tensorlayer

**Comment by zsdonghao** [comment]
Logging need to set a verbosity level, normally TL set this value by default on "INFO" level 

add these two lines in your code.

```python
tf.logging.set_verbosity(tf.logging.DEBUG)
tl.logging.set_verbosity(tl.logging.DEBUG)
```
