### ISSUE TITLE
duplicated codacy webhook

### ISSUE THREAD

**Issue by lgarithm** [tensorlayer/tensorlayer#707]
I found that we have configured two codacy webhooks:

https://github.com/tensorlayer/tensorlayer/settings/hooks

They belong to

* https://app.codacy.com/organization/tensorlayer
* https://app.codacy.com/app/DEKHTIARJonathan/tensorlayer

respectively

**Comment by lgarithm** [comment]
@DEKHTIARJonathan I've added you as the admin of https://app.codacy.com/organization/tensorlayer.
Could you delete https://app.codacy.com/app/DEKHTIARJonathan/tensorlayer?

I can't tell which one is which from the webhook URLs.

**Comment by DEKHTIARJonathan** [comment]
@lgarithm I have removed it. Could you check ?

**Comment by zsdonghao** [comment]
@lgarithm removed
