### ISSUE TITLE
Run CI in docker

### ISSUE THREAD

**Issue by lgarithm** [tensorlayer/tensorlayer#708]
### New Issue Checklist

- [X] I have read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [X] I searched for [existing GitHub issues](https://github.com/tensorlayer/tensorlayer/issues)

### Issue Description

The base image used by travis CI is pretty old, which makes it hard to install modern packages, (e.g. a relatively new version of openmpi, required by horovod).
On the other hand, we release docker images but never had them tested.

So I'm think of running our tests in docker, it can solve both of the problems above.

**Comment by lgarithm** [comment]
For the problem of installing openmpi, I have some solutions in mind for it.

But I feel like running test in docker would be an elegant way to go in our long term plan.

**Comment by lgarithm** [comment]
In short term, I have to solve the problem of running TL program in classical environment anyway, because Read The Doc is also classical.

**Comment by DEKHTIARJonathan** [comment]
In case you need, you can use lazy loading

**Comment by lgarithm** [comment]
`LazyImport` doesn't work for document. 
When we run doc test on travis-ci, or build doc on RTD, horovod has to be imported, and its dependency openmpi has to be installed.

**Comment by DEKHTIARJonathan** [comment]
Yeap, LazyImport is bypassed for documentation building ;)
I believed it was a good idea, maybe it is not necessary and we can remove this feature.

**Comment by lgarithm** [comment]
Yet another reason to run tests in docker in that, you can easily run the tests locally.
Currently we have a complex combination of requirement files, 
when the core team do large scale changes, it's very hard to run a full test locally.

**Comment by DEKHTIARJonathan** [comment]
@lgarithm for information Travis runs a Docker image.
Requirements files are splitted to allow a finer control on dependencies.

As a TL developer, the **only way** you should install tensorlayer for development are the following commands:
```shell
# for a machine **without** an NVIDIA GPU
pip install -e .[all_cpu_dev] --upgrade

# for a machine **with** an NVIDIA GPU
pip install -e .[all_gpu_dev] --upgrade
```

See [Contributing.md](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md#build-from-sources)

If you follow this pattern, I don't see what are the benefits of doing this. The Docker containers are not build with the test dependencies ... And are not suited for test today. CircleCI is really difficult to use and totally unintuitive. Leaving TravisCI (which is an OpenSource standard) to run the tests on CircleCI building the docker images is for me a bad idea.

**Comment by lgarithm** [comment]
@DEKHTIARJonathan I didn't mean to leave TravisCI.
The way I'd like to do it would be roughly like:

```yaml
services:
- docker

# TODO: add compatibility matrix
before_install:
- docker build --rm -t tensorlayer:snapshot -f docker/Dockerfile.test .

script:
- docker run --rm -it tensorlayer:snapshot pytest
```

* enable [docker service](https://docs.travis-ci.com/user/docker/) in travis.yml 
* build a temporary docker image on travis CI
* run tests inside the temporary image

Then you will be able to reproduce what exactly happened on travis-ci by typing the following commands:

```bash
docker build --rm -t tensorlayer:snapshot -f docker/Dockerfile.test .
docker run --rm -it tensorlayer:snapshot pytest
```

I think this way is more hermetic, and portable. (This is exactly what docker tries to solve.)
Because the installation of python can be different on our dev machines,
For me, the command I type is `pip3` rather that `pip`, 
and maybe for other people, root is required to run pip, etc.

**Comment by DEKHTIARJonathan** [comment]
To be honest, I really don't see the benefits ... 

#### about `pip3`

If you have to use `pip3` or `python3` it means that you don't use a `virtualenv` as recommended in [Contributing.md](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md#build-from-sources).

#### concerning doing it in Travis

We never had any bug happening in Travis and not in a local machine. I would agree with you if we had such an issue (it would be problematic not being able to reproduce a bug). However, I'm not aware of any issue of this kind. Adding layers of complexity, if not necessary, only tend to make the project more difficult for newcomers. Having to install docker (which is **highly unstable** on windows) in order to add a simple function seem very overkill to me.
