### ISSUE TITLE
KeyError: 'params is not a file in the archive'

### ISSUE THREAD

**Issue by ousay** [tensorlayer/tensorlayer#716]
i am a rookie，so sorry....
i tried to read the npyio.py and utils.py ,but it is  hard for me to find the way to solve it
### Issue Description
KeyError: 'params is not a file in the archive'
i am studying tensorlayer books，chapter5: word2vec
after training，here exist model_word2vec_50k_128.npz ，vocab_text8.txt,  word2vec.py.  but when i restore npz  , cause err
### Reproducible Code

- Which OS are you using ?
ubuntu16 python3.5 tensorflow==1.8.0
tensorlayer==1.9.0

[INSERT CODE HERE]

```python
# ======================================================== #
###### THIS CODE IS AN EXAMPLE, REPLACE WITH YOUR OWN ######
# ======================================================== #

import tensorlayer as tl
import tensorflow as tf
sess = tf.InteractiveSession()
def main_restore_embedding_layer():
    vocabulary_size = 50000
    embedding_size = 128
    model_file_name = "model_word2vec_50k_128"
    batch_size = None

    print("Load existing embedding matrix and dictionaries")
    all_var = tl.files.load_npy_to_any(name=model_file_name + '.npy')
    data = all_var['data']
    count = all_var['count']
    dictionary = all_var['dictionary']
    reverse_dictionary = all_var['reverse_dictionary']

    tl.nlp.save_vocab(count, name='vocab_' + model_file_name + '.txt')

    del all_var, data, count

    x = tf.placeholder(tf.int32, shape=[batch_size])

    emb_net = tl.layers.EmbeddingInputlayer(x, vocabulary_size, embedding_size, name='emb')

    # sess.run(tf.global_variables_initializer())
    tl.layers.initialize_global_variables(sess)

    haha=tl.files.load_and_assign_npz(sess=sess, name=model_file_name+'.npz', network=emb_net)

    emb_net.print_params()
    emb_net.print_layers()
main_restore_embedding_layer()

# ======================================================== #
###### THIS CODE IS AN EXAMPLE, REPLACE WITH YOUR OWN ######
# ======================================================== #
```

err detial:

wy@wy-virtual-machine:~/word2vec$ python T_sne_word2vec.py
Load existing embedding matrix and dictionaries
[TL] WARNING: From T_sne_word2vec.py:29: initialize_global_variables (from tensorlayer.layers.utils) is deprecated and will be removed after 2018-09-30.
Instructions for updating: This API is deprecated in favor of `tf.global_variables_initializer`

Traceback (most recent call last):
  File "T_sne_word2vec.py", line 35, in <module>
    main_restore_embedding_layer()
  File "T_sne_word2vec.py", line 31, in main_restore_embedding_layer
    haha=tl.files.load_and_assign_npz(sess=sess, name=model_file_name+'.npz', network=emb_net)
  File "/home/wy/.local/lib/python3.6/site-packages/tensorlayer/files/utils.py", line 1703, in load_and_assign_npz
    params = load_npz(name=name)
  File "/home/wy/.local/lib/python3.6/site-packages/tensorlayer/files/utils.py", line 1636, in load_npz
    return d['params']
  File "/home/wy/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 239, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'params is not a file in the archive'

**Comment by zouqy** [comment]
Is the err solved? please help me~~ ,  I have ths same problem~_~!

**Comment by ousay** [comment]
@zouqy 
sorry  i  did not mark it，so  i cannot remember it clearly. maybe you can  check you tensorlayer version,lower version sometimes better for some issues.

**Comment by zouqy** [comment]
i just figure it out , please check here, this is my learning blog, but chapter3_3.5_2~9渐变, i cannot figure it out stil, could you help me? many thanks：
https://blog.csdn.net/weixin_42025210/article/details/81906595

**Comment by Eminencetoosure** [comment]
i don't know if you are able to figure it out.. I'd be glad to have the solution.
