### ISSUE TITLE
New tutorial example for Memory network (memn2n)

### ISSUE THREAD

**Issue by zergxyz** [tensorlayer/tensorlayer#73]
Can we add an example in our tutorial for the end-2-end Memory Network (like this one in pure tensorflow: https://github.com/domluna/memn2n )
I think an example to demo  Memory Network and neural attention mechanism is important for our framework, thanks.

**Comment by zsdonghao** [comment]
@zergxyz  Good idea, I already label this issue as `help wanted`.

If anyone want to work on this, I can help.
