### ISSUE TITLE
Add ELMo (Deep contextualized word representations)

### ISSUE THREAD

**Issue by chengrufeng** [tensorlayer/tensorlayer#748]
## Introduction
ELMo is a deep contextualized word representation that models both (1) complex characteristics of word use (e.g., syntax and semantics), and (2) how these uses vary across linguistic contexts (i.e., to model polysemy). These word vectors are learned functions of the internal states of a deep bidirectional language model (biLM), which is pre-trained on a large text corpus. They can be easily added to existing models and significantly improve the state of the art across a broad range of challenging NLP problems, including question answering, textual entailment and sentiment analysis.

### Other Tools

- [ ] [allenai](https://github.com/allenai/bilm-tf)
- [ ] [elmo](https://allennlp.org/elmo)

### Issue Description

It's not easy to use them.
I need a more simple and convenient tool like "Word2Vec" in "gensim"

**Comment by DEKHTIARJonathan** [comment]
Thanks for your suggestion, unfortunately we are quite busy right now. The easiest way to have it available as soon as possible would be to implement it yourself and open a PR.

We would be very happy to receive a PR from you implementing it ;)

**Comment by zsdonghao** [comment]
checkout https://github.com/tensorlayer/tensorlayer/releases/tag/2.0.0
