### ISSUE TITLE
Typo in absolute different error function

### ISSUE THREAD

**Issue by thangvubk** [tensorlayer/tensorlayer#753]
### New Issue Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/tensorlayer/tensorlayer/issues)

### Issue Description

[Typo in absolute different error function]

``def absolute_difference_error(output, target, is_mean=False, name="mean_squared_error_loss")``
Here, ``name`` should be changed to ``absolute_difference_error_loss``. It makes confusion on tensorboard graphs.

**Comment by luomai** [comment]
Could you make a PR to modify this? Thanks! Your contribution is highly appreciated.

**Comment by DEKHTIARJonathan** [comment]
Fix implemented in #759
