### ISSUE TITLE
load_cifar10_dataset logging error

### ISSUE THREAD

**Issue by limingzhan0904** [tensorlayer/tensorlayer#764]
My device env is: 
win10 64 bit
python 3.6.2
tensorflow 1.8

my code is:

```python
`X_train, y_train, X_test, y_test = tl.files.load_cifar10_dataset(shape=(-1, 32, 32, 3),
                                                                 path='X',
                                                                 plotable=True)
a  = tf.shape(X_train)
x1 =sess.run(a)
print(x1)`
```

error msg:
` File "C:\install\Anaconda3\envs\tensorflow\lib\site-packages\tensorlayer\files\dataset_loaders\cifar10_dataset.py", line 104, in load_cifar10_dataset
    logging.info('Shape of a training image: X_train[0] %s' % X_train[0].shape)
TypeError: not all arguments converted during string formatting`

Please help, thanks a lot.

**Comment by zsdonghao** [comment]
fixed by 2.0.0 version
