### ISSUE TITLE
Adaptive Instance Normalization [Extra Documentation request]

### ISSUE THREAD

**Issue by ArturoDeza** [tensorlayer/tensorlayer#800]
Hi, the results from the AdaIN implementation look amazing, and I'm looking forward to using them in some of my work. Would you be able to post a code demo in the AdaIN link: https://github.com/tensorlayer/tensorlayer/tree/master/example/adaptive_style_transfer

I'd also like to request the following versions that were used to generate the results (as these usually make a difference in the rendering quality of image samples related to style transfer research)

```
CUDA
CUDNN
tensorflow
tensorlayer
python (2 or 3?)
gcc
```

**Comment by JunbinWang** [comment]
Well,  as long as you install Tensorflow and Tenlayer successfully, you can run the code with Python3.
For Tensor-GPU version, of course you need CUDA, CUDNN.

**Comment by ArturoDeza** [comment]
Hi @JunbinWang , thanks! Sure I was referring to the versions of CUDA and CUDNN used with tensorflow and tensorlayer (as well as their versions), apologies for not being clear on the request. I know that tensorflow sometimes does not have backwards compatibility or the name of functions change after each version so I wanted to be aware of any possible bugs I might encounter that are version dependent.

**Comment by JunbinWang** [comment]
@ArturoDeza I didn't encounter any version dependent problem. When you make sure you can 'import tensorlayer as tl, tensorflow as tl'  correctly in your python3 environment, then I think it would be enough to run my code.
If you encounter any problems later, you can pose here, maybe I can help : )

**Comment by zsdonghao** [comment]
The project is now moved to https://github.com/tensorlayer/adaptive-style-transfer
