### ISSUE TITLE
The class  called "TernaryConv2d" missing the defination of its outputs,there would be some error.

### ISSUE THREAD

**Issue by edwardzcl** [tensorlayer/tensorlayer#816]
When I define model as below using function -- TernaryConv2d, then we get some errors.

                         ... ...
    with tf.variable_scope("binarynet", reuse=reuse):
        net = tl.layers.InputLayer(x, name='input')
        net = tl.layers.TernaryConv2d(net, 16, (5, 5), (1, 1), padding='VALID', b_init=None, name='bcnn1')
        net = tl.layers.MaxPool2d(net, (2, 2), (2, 2), padding='SAME', name='pool1')
        net = tl.layers.BatchNormLayer(net, act=tl.act.htanh, is_train=is_train, name='bn1')
                      ... ...

The errors may be like 
''  File "E:\python\lib\site-packages\tensorlayer\layers\binary.py", line 542, in __init__
    data_format=data_format
  File "E:\python\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 725, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "E:\python\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 528, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 'input' to a tensor and failed. Error: None values not supported."

I found this is because the defination of class called ''TernaryConv2d'' missed a line of code ''self.inputs = prev_layer.outputs '' in TL version 1.8.5.

You can solve this problem by adding the  code above at the place of the class defination. Thank you~

**Comment by DEKHTIARJonathan** [comment]
Can u check with the latest version of TensorLayer?
It's version 1.9.1

**Comment by edwardzcl** [comment]
I see.The latest version contain the line of code in super class "Layer" ,altogether,but the previous version did not.Thank you .

**Comment by edwardzcl** [comment]
You can not deny there is the negligence which i had descripted  in TL version 1.8.5. I am exactly a old player of TL,because not all people want to use the latest version.
