### ISSUE TITLE
the out_size of deconv2d

### ISSUE THREAD

**Issue by liumarcus70s** [tensorlayer/tensorlayer#834]
Hello everybody,

The parameter “out_size” in function DeConv2D was removed, but how can I refer the outsize now?
 
I want Deconv a 4X3 matrix to 7X5, but the output size is 8X6 even I set the "out_size" to (7,5).

Any solutions?

**Comment by zsdonghao** [comment]
the stride value will control the output size.

**Comment by liumarcus70s** [comment]
but the input is 4X3 and the output I need is 7X5, not 8X6

**Comment by liumarcus70s** [comment]
tried, invalid  : (

**Comment by wagamamaz** [comment]
Could you put your code here?

**Comment by zsdonghao** [comment]
feel free to reopen if you want to discuss.

we just release 2.0.0 version
