### ISSUE TITLE
Can not import tensorlayer!

### ISSUE THREAD

**Issue by JobSmith** [tensorlayer/tensorlayer#854]
![image](https://user-images.githubusercontent.com/15700681/46239612-3b92f980-c3cd-11e8-9a5c-77ddee344b35.png)
As the picture show, importing the tensorlayer is failed.
It doesnt show any error info.

**Comment by DEKHTIARJonathan** [comment]
I don't understand the problem. Try recreating the virtualenv.
The issue is clearly on your side, you are the only one having this issue.

**Comment by initial-h** [comment]
i meet with it too.
![1539869406 1](https://user-images.githubusercontent.com/27199383/47157933-0c610f80-d31d-11e8-9122-476f05327d61.png)

**Comment by fangde** [comment]
it seems both of you work on windows, we have not test tl on windows, to my knowlege.

**Comment by zsdonghao** [comment]
@fangde John use windows

**Comment by DEKHTIARJonathan** [comment]
I use both. But the issues is with your python install
