### ISSUE TITLE
No respond for tl.vis.read_images()

### ISSUE THREAD

**Issue by fiy2W** [tensorlayer/tensorlayer#856]
### New Issue Checklist

- [ ] I have read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [ ] I searched for [existing GitHub issues](https://github.com/tensorlayer/tensorlayer/issues)

### Issue Description

The function `tl.vis.read_images` works well on tensorlayer 1.8, but in trouble on tensorlayer 1.9 and above. When I use this function to load a large number of images, e.g. 2000, it will return a `warning` for `imageio` and do not respond.
If I replace `imageio.imread` in the function with `scipy.misc.imread`, it works again like tensorlayer 1.8

### Reproducible Code

- Ubuntu 16.04
- Python 2.7
- tensorlayer 1.9 and above

```python
# ======================================================== #
############### THIS CODE IS AN EXAMPLE ####################
# ======================================================== #

import tensorlayer as tl

file_list = ['1.tif', '2.tif', '3.tif', ...]  # a list for image names
im_dir = 'images/'  # path to images
imgs = tl.vis.read_images(file_list, path=im_dir, n_threads=32)

# ======================================================== #
############### THIS CODE IS AN EXAMPLE ####################
# ======================================================== #
```

**Comment by DEKHTIARJonathan** [comment]
@zsdonghao can you have a look ?

**Comment by zsdonghao** [comment]
Yes, let's open a PR for this.

**Comment by zsdonghao** [comment]
feel free to reopen if you want to discuss.

we just release 2.0.0 version
