### ISSUE TITLE
Bug in UpSampling2dLayer，tf.shape(xxx) will get None axis

### ISSUE THREAD

**Issue by One-sixth** [tensorlayer/tensorlayer#899]
### New Issue Checklist

- [ ] I have read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/tensorlayer/tensorlayer/issues)

### Issue Description

When I use UpSampling2dLayer, the outputs shape is [None, None, None, number]
It should use self.inputs.shape instead of tf.shape(self.inputs).

### Reproducible Code

- Which OS are you using ?
win10
- Please provide a reproducible code of your issue. Without any reproducible code, you will probably not receive any help.

[INSERT CODE HERE]

```python
# ======================================================== #
###### THIS CODE IS AN EXAMPLE, REPLACE WITH YOUR OWN ######
# ======================================================== #

import tensorflow as tf
import tensorlayer as tl

a=tf.placeholder(tf.float32, [None, 4, 4, 3])
b=tl.layers.InputLayer(a)
c=tl.layers.UpSampling2dLayer(b, (2,2))
print(c.outputs.shape)

**Comment by zsdonghao** [comment]
@One-sixth hi, which version of TL are you using? I remember this problem happen before, but @DEKHTIARJonathan has fixed this in the latest version.

**Comment by One-sixth** [comment]
I I just updated my tensorlayer to 1.11.1 and the problem still exists.
c.outputs.shape still is (?, ?, ?, 3)

**Comment by zsdonghao** [comment]
Hi, it is not a bug. In doing so, up-sampling layer support dynamic input size.

**Comment by One-sixth** [comment]
Thank your work.
