### ISSUE TITLE
tl.files.load_and_assign_npz() does not return 'False'

### ISSUE THREAD

**Issue by ImpactCrater** [tensorlayer/tensorlayer#918]
### New Issue Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/tensorlayer/tensorlayer/issues)

### Issue Description

tl.files.load_and_assign_npz() does not return 'False' when the model is not exist.
I tried to add 'return False' to the code and it works well.
tensorlayer/files/utils.py

```python
def load_and_assign_npz(sess=None, name=None, network=None):


    if not os.path.exists(name):
        logging.error("file {} doesn't exist.".format(name))
        return False
```

### Reproducible Code

- Which OS are you using ?
 Ubuntu 16.04 LTS

```python
    if tl.files.load_and_assign_npz(sess=sess, name=checkpoint_path + 'g_{}.npz'.format(tl.global_flag['mode']), network=net_g) is False:
        tl.files.load_and_assign_npz(sess=sess, name=checkpoint_path + 'g_{}_init.npz'.format(tl.global_flag['mode']), network=net_g)
```

**Comment by zsdonghao** [comment]
@ImpactCrater thanks, it would be great if you can make a push request

**Comment by ImpactCrater** [comment]
@zsdonghao thank you very much!
