### ISSUE TITLE
multi-machine example?

### ISSUE THREAD

**Issue by innerop** [tensorlayer/tensorlayer#920]
hi,

I found this 

https://github.com/tensorlayer/tensorlayer/blob/master/examples/distributed_training/tutorial_cifar10_distributed_trainer.py 

but it does not mention how to setup a cluster, and hat distribution strategy it uses (PS, AllReduce, etc?)

Can you clarify?

**Comment by zsdonghao** [comment]
it use horovod, you can setup via https://github.com/tensorlayer/tensorlayer/tree/master/scripts

hope it help

**Comment by innerop** [comment]
yes, thank you
