### ISSUE TITLE
Is there a mistake of port in ReadME (Docker GPU install) ?

### ISSUE THREAD

**Issue by William-Mou** [tensorlayer/tensorlayer#922]
Hello, when I try to install tensorlayer with nvidia-docker, I find an error port in Documentation.

![](https://i.imgur.com/bySvwrT.png)

`nvidia-docker run -it --rm -p 8888:88888 -p 6006:6006 -e PASSWORD=JUPYTER_NB_PASSWORD tensorlayer/tensorlayer:latest-gpu
`

As is known to me, It should be 8888 port for jupyter notebook (default) , like this.

`nvidia-docker run -it --rm -p 8888:8888 -p 6006:6006 -e PASSWORD=JUPYTER_NB_PASSWORD tensorlayer/tensorlayer:latest-gpu
`

thank you!

**Comment by DEKHTIARJonathan** [comment]
Indeed
