### ISSUE TITLE
Potential bug in deformable conv

### ISSUE THREAD

**Issue by bowenc0221** [tensorlayer/tensorlayer#934]
https://github.com/tensorlayer/tensorlayer/blob/aa9e52e36c7058a7e6fd81d36563ca6850b21956/tensorlayer/layers/convolution/deformable_conv.py#L110-L112

Does this code miss a `axis=-1` in `tf.stack`?

**Comment by zsdonghao** [comment]
feel free to reopen if you want to discuss.

we just release 2.0.0 version
