### ISSUE TITLE
Runtime increase for commands: tl.layers.initialize_global_variables(sess) AND tl.files.load_and_assign_npz

### ISSUE THREAD

**Issue by mahmed0509** [tensorlayer/tensorlayer#945]
### New Issue Checklist

- [ y] I have read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [ y] I searched for [existing GitHub issues](https://github.com/tensorlayer/tensorlayer/issues)

### Issue Description

I have the following lines of code in a def which is called inside a for loop in another def. I am seeing a runtime increase for the commands below as the number of iterations are increasing. 

tl.layers.initialize_global_variables(sess)
tl.files.load_and_assign_npz(sess=sess, name=checkpoint_dir +'/'+ checkpoint_name, network=net_g)

### Reproducible Code

- Which OS are you using ?
- Please provide a reproducible code of your issue. Without any reproducible code, you will probably not receive any help.

```python
# ======================================================== #
###### CODE ######
# ======================================================== #

import tensorflow as tf
import tensorlayer as tl

def test_image :
#### Few lines of code #######
   with tf.Session(config=tfconfig) as sess:
      #### RUNTIME increases with iterations for the TWO lines below ########
        tl.layers.initialize_global_variables(sess)
        tl.files.load_and_assign_npz(sess=sess, name=checkpoint_dir +'/'+ checkpoint_name, network=net_g)

def test:
##### few lines of code ##########
   for <iterating over a list of images>
         test_image <each image>


# ======================================================== #
###### CODE ######
# ======================================================== #
```

**Comment by zsdonghao** [comment]
feel free to reopen if you want to discuss.

we just release 2.0.0 version
