### ISSUE TITLE
Warning in tensorlayer.layers.utils.set_name_reuse

### ISSUE THREAD

**Issue by rupalkapdi** [tensorlayer/tensorlayer#949]
Hello Hao Dong,

I am using your library for my project on tumor segmentation. The code has stopped working because of the issue of tensorlayer.layers.utils.set_name_reuse. 

How to solve this issue?

Thank you.

**Comment by zsdonghao** [comment]
`tensorlayer.layers.utils.set_name_reuse` is removed, I think you can just delete it

**Comment by rupalkapdi** [comment]
Thanks for your reply.
